### ISSUE TITLE
Enable windows executables to be distributed via Winget

### ISSUE THREAD

**Issue by akshaybharambe14** [profclems/glab#103]
Microsoft has released Winget cli tool to install and manage windows programs. The glab windows executables can be distributed via this tool.

Link to Winget project 
https://github.com/microsoft/winget-cli

**Comment by profclems** [comment]
Never heard of winget till now. Seems it's still in preview stage and available only for those on windows insiders.
Thanks, I'll work on that in the next release, however, I will be glad if you'd want to take this up 😃

**Comment by akshaybharambe14** [comment]
Sure, I will open a PR for this.

**Comment by profclems** [comment]
Great... We'll be looking forward to that

**Comment by profclems** [comment]
@akshaybharambe14 are you still up for this??

This should help: https://github.com/microsoft/winget-pkgs#submitting-a-package
