### ISSUE TITLE
Color is not reset on mr list if last branch is ellipsed

### ISSUE THREAD

**Issue by iggyvolz** [profclems/glab#106]
**Description**

If the branch for the final MR is too long to be listed, blue color is not ended at the end of the line and 

**Expected Behavior**

The `[0m` element should always close the color even if it is ellpised.

**Actual Behavior**
There is no `[0m` element, leading the next line to retain its color

**Possible Fix**
Error appears to be in https://github.com/profclems/glab/blob/606ba7dd2bb866c55af0eab1410707f18e0852a5/commands/mr.go#L23 - it seems that MaxColWidth is cutting off the end of color element.

**Steps to Reproduce**
1. Clone https://gitlab.com/iggyvolz/repo-with-long-branch-name
2. Run glab mr list
3. The terminal is colored blue:
```
Showing mergeRequests 1 of 1 on iggyvolz/repo-with-long-branch-name

[0;32m#1[0m	My Merge Request	[0;36m(master) ← (this-is-a-really-long-branch-name-and-it-will-cau...      
```

**Context**

**Your Environment**

* Version used:
```
glab version v1.9.1 (08/17/2020)
git version 2.28.0
Made with ❤ by Clement Sam <clementsam75@gmail.com> and contributors
```
* Operating System and version: Arch Linux (rolling)

**Comment by profclems** [comment]
@iggyvolz thanks for reporting this issue...

**Comment by profclems** [comment]
@iggyvolz while we work on fixing this kindly refer to this comment https://github.com/profclems/glab/issues/258#issuecomment-705941793 for a quick fix

**Comment by zemzale** [comment]
This seems to be fixed with the newest releases, where pager for displaying merge request lists.
```
Showing 1 open merge request on iggyvolz/repo-with-long-branch-name (Page 1)

!1  My Merge Request  (master) ← (this-is-a-really-long-branch-name-and-it-will-cau...
```

I would imagine we could expand the size the output depending on the size of the terminal, since it cuts off before reaching half of my terminal size, but that is out of scope for this issue.

**Comment by profclems** [comment]
> I would imagine we could expand the size the output depending on the size of the terminal, since it cuts off before reaching half of my terminal size, but that is out of scope for this issue.

Yeah I agree with you @zemzale. Kindly open a separate issue for this then we see how best we can resolve this issue
