### ISSUE TITLE
pipeline view ci glitches

### ISSUE THREAD

**Issue by sattellite** [profclems/glab#116]
**Description**

The screen is not drawn correctly when I return to it from the job traces screen. And after that glitch glab not responding to any key press, like freezes.

**Expected Behavior**

I want see correct main screen after return from job traces.

**Actual Behavior**

Go to "production build" block. View job traces.

![image](https://user-images.githubusercontent.com/322910/90607142-801a1f00-e209-11ea-9a2c-9e0df4de98a4.png)

What I see when return to main screen by pressing <kbd>q</kbd>.

![image](https://user-images.githubusercontent.com/322910/90607176-8a3c1d80-e209-11ea-8315-116f7640d44c.png)

**Steps to Reproduce**
1. `glab pipeline view ci`
2. Select any job by keyboard arrows and open it by <kbd>Enter</kbd>
3. Return to main screen by pressing <kbd>q</kbd>

**Environment**

* Version used: latest version from sources 2b91d30
* Operating System and version: MacOS Catalina 10.15.6, iTerm2 3.3.12

**Comment by sattellite** [comment]
Also I catch freezes on main screen when job finished and pipeline goes to next job. glab not responding to any key press too. `pkill glab` helps only.

**Comment by profclems** [comment]
Sorry about this... I'll get this fixed asap.
I think the problem comes from mishandled keybindings. Use <kbd>Enter</kbd> to toggle in and out of the job log view and let me know if it works on your side without failure.

**Comment by sattellite** [comment]
<kbd>Enter</kbd> works correctly.

**Comment by profclems** [comment]
Okay. I will get it fixed asap and do a patch release
