### ISSUE TITLE
Organize commands to folders

### ISSUE THREAD

**Issue by pgollangi** [profclems/glab#157]
With increasing number of commands, its becoming difficult look through commands and when tests included to commands, entire `./commands` folder become messy.

We can group all secondary commands of a primary command to one folder.

**Describe the solution you'd like**
Folder structure would be:
```
commands
│   root.go
│   version.go
│
└───issue
│   │   issue.go
│   │   issue_list.go
│   
└───mr
    │   mr.go
    │   mr_list.go
```

**Describe alternatives you've considered**
Package to classify all primary commands to one is also possible.

This change best done when no open PRs modifying commands to avoid rework

**Comment by profclems** [comment]
I agree with this. We really need to write tests for the commands but the commands folder will look quite messy with that so restructuring will help us.
However, there's currently an open PR by @BreD1810 to resolve #108. We would have to wait then. 

By the way, we have a minor release (v1.10.0) to do this Weekend 🎉

**Comment by BreD1810** [comment]
I've become fairly busy since making that PR. It may be best to go ahead with this change, and I can merge/start fresh with #113 when I have more time. Otherwise, you might be waiting for a while.

Looking forward to the release :)

**Comment by pgollangi** [comment]
Thanks @BreD1810 for sharing status on #113 
@profclems I think I can take up this after v1.10.0 release.

**Comment by pgollangi** [comment]
@profclems what would you think if I make this change now(possibly tomorrow)? Since I don't see many open PRs and we are heading to add more test coverage.

**Comment by profclems** [comment]
Okay sure... I'll merge the recent PR today.
However, there are a few concerns we must take into consideration. We might need to change the code structure so that each sub-package doesn't introduce cyclic dependencies.

**Comment by profclems** [comment]
@pgollangi in order to enhance restructuring the commands folder into separate units and write better tests, I'm currently rewriting the config package which I will open a PR soon to cover.
Also to avoid introducing cyclic dependencies, I will create a factory package that initializes the needed functions and passes them to the `commands/*`

**Comment by pgollangi** [comment]
@profclems Its only good to make restructuring command after #223 and even organizing commands as part of #223 would make sense to me.
