### ISSUE TITLE
Ability to list issues assigned to a user

### ISSUE THREAD

**Issue by profclems** [profclems/glab#168]
Follows a similar format as  #167

**Comment by j-mcavoy** [comment]
This API call for listing issues for a assignee username are supported on GitLab's API but is missing from go-gitlab's API, I made a PR and issue https://github.com/xanzy/go-gitlab/issues/925

Once this is sorted out, the following should work:
https://github.com/profclems/glab/compare/trunk...j-mcavoy:168_list_issues_assigned_to_a_user

**Comment by profclems** [comment]
Yeah I just checked the PR and it's a relevant change you've made. You can open a PR once it's accepted
