### ISSUE TITLE
Support for shell completions.

### ISSUE THREAD

**Issue by profclems** [profclems/glab#174]
`glab` uses cobra. Cobra has support for generating bash and zsh autocompletion here: https://github.com/spf13/cobra/blob/master/bash_completions.md

***Edit:***

> It seems cobra has support for bash, zsh, fish and powershell. It may be best just to support all 4. - @BreD1810 

Targetted Shells
* Bash
* Zsh
* Fish
* Powershell

Reference: https://github.com/spf13/cobra/blob/master/shell_completions.md

**Comment by BreD1810** [comment]
Could we add fish to the list please? It's very popular too.

It seems cobra has support for bash, zsh, fish and powershell. It may be best just to support all 4.
https://github.com/spf13/cobra/blob/master/shell_completions.md

**Comment by profclems** [comment]
Yeah sure... We should work on all 4 then

**Comment by profclems** [comment]
Do you think support for aliases will be feasible?
Seems there are limitations in zsh, fish and powershell in terms of custom completion

**Comment by BreD1810** [comment]
From what I have seen before, a completion script is used which calls `glab` to determine what commands are available. I'll have to have a look into how cobra determines what commands to give back to the completion script, but in theory it should be possible to append a list of aliases to the suggestions.
