### ISSUE TITLE
GITLAB_URI environment variable not set by default, leads to "unsupported protocol scheme" error

### ISSUE THREAD

**Issue by dnsmichi** [profclems/glab#184]
**Description**

I was trying this nice project and started with the minimum effort - short install and only the required settings.

After setting the GITLAB_TOKEN environment variable, I changed into a GitLab repository and ran `glab pipeline list` to see the CI/CD status. 

There I was greeted with this error:
![image](https://user-images.githubusercontent.com/382049/91715714-82c42f00-eb8e-11ea-97cf-5b0299de8a76.png)

**Expected Behavior**

The `GITLAB_URI` environment variable is set to `https://gitlab.com` as stated in the documentation: https://github.com/profclems/glab#environment-variables 

```
GITLAB_URI: specify the url of the gitlab server if self hosted (eg: https://gitlab.example.com). 
Default is https://gitlab.com.
Can be set with `glab config --url=gitlab.example.com`
```

**Actual Behavior**

The GitLab URI is not set, and as such, the request URL does not match the expected string. This results in a strange error that the protocol is not supported.

```
glab pipeline list -s success
Error: Get "/api/v4/projects/dnsmichi%2Fci-monitoring-webcast-2020/pipelines?page=1&per_page=20&sort=desc&status=success": unsupported protocol scheme ""
```

After setting `GITLAB_URI` via command line, this worked.

![image](https://user-images.githubusercontent.com/382049/91715887-dfbfe500-eb8e-11ea-85d4-e8d1b8f1cd63.png)

**Possible Fix**

If `GITLAB_URI` is not set, prefer the default `https://gitlab.com`. 

**Steps to Reproduce**

1. Install glab via Homebrew
2. Change into a GitLab project  
3. Run `glab pipeline list`

**Context**

Initial project test, trying some of the commands. This is a global problem, `glab release list` doesn't work either. I haven't looked into the code yet but have seen that there are major refactorings for configuration going on. 

**Your Environment**

* Version used: 1.10 via Homebrew
* Operating System and version: macOS Catalina 10.15.6 

```
glab --version
glab version 1.10.0 ()
git version 2.28.0
Made with ❤ by Clement Sam <clementsam75@gmail.com> and contributors
```

**Comment by Dentrax** [comment]
I'm getting exact same issue:

**Steps to Reproduce**
1. Install **glab** via _Homebrew_
2. `glab config --token=<YOUR-GITLAB-ACCESS-TOKEN>`
3. `glab config --url=gitlab.example.com`
4. `glab pipeline list`
5. See the error: `Error: Get "gitlab.foo.com/api/v4/projects/bar%2Fbaz/pipelines?page=1&per_page=20&sort=desc": unsupported protocol scheme ""`

But when i send a **GET** request that **URL** with **cURL**, i can able to _successfully_ parse the whole **JSON** body:
```sh
$ curl -s -L -X GET "<URL>" | jq
```

**Comment by profclems** [comment]
@dnsmichi thanks for reporting this issue. I'll have this fixed asap.

@Dentrax Sorry you had this issue. Make sure you include the protocol (https or http) in the GITLAB_URI; for example:
```sh
glab config -g --url=https://gitlab.example.com
```
You can also just run `glab config -g` and follow the prompt to verify and set the configuration
