### ISSUE TITLE
Support XDG Base Directory spec for configuration files

### ISSUE THREAD

**Issue by zemzale** [profclems/glab#186]
**Is your feature request related to a problem? Please describe.**
There is a [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for where different type of files should be. The main thing to this project is the configuration files. This allows for decluttering the home directory and having all the config files in one place.

**Describe the solution you'd like**
Glab should try to read configuration files from directory specified in `$XDG_CONFIG_HOME` or default to `$HOME/.config` if this environment variable is empty as per spec.

If there is no configuration there it should still try to read form `$HOME/.glab-cli` like it does now to not break backwards compatibility.

**Comment by profclems** [comment]
Thanks @zemzale 
I would appreciate if you would want to take this up with a quick PR 😉
