### ISSUE TITLE
glab mr approve can't work

### ISSUE THREAD

**Issue by wilsonjwz** [profclems/glab#187]
first 
`glab mr create -t patch -d patch -b test`

get
`#1794 patch (feature/xxx) less than a minute ago`

and
`glab mr approve 1794`

get
`Approving Merge Request #1794...
404 Not Found`

i want get the resason

**Comment by wilsonjwz** [comment]
version: GitLab Community Edition 10.0.3

**Comment by wilsonjwz** [comment]
@profclems  can you print the gitlab http request

**Comment by profclems** [comment]
@wilsonjwz sorry you're faced with this issue.

I can't pinpoint exactly where the issue is coming from. The GitLab API changes. 
Check if you entered the correct merge request ID. Also, make sure you have permission to approve merge requests

**Comment by wilsonjwz** [comment]
ok my friend  I will debug it until I can merge it

**Comment by profclems** [comment]
You can also try merging to see if it errors as well with:
```sh
glab mr merge 1794
```

**Comment by wilsonjwz** [comment]
thank you very much my friend  
I misread the command for `approve ` actually `merge `
If the examples in the document can be enriched, it will be clear
