### ISSUE TITLE
Aliases can be made with the names of commands

### ISSUE THREAD

**Issue by BreD1810** [profclems/glab#194]
Currently, you can set an alias with the same name as the command. The alias will not work, but it will be created anyways.

![image](https://user-images.githubusercontent.com/32489229/92146271-608e1380-ee11-11ea-9c28-5558f9745825.png)

Instead, there should be an error shown to the user, similar to the GitHub CLI:

![image](https://user-images.githubusercontent.com/32489229/92146408-9206df00-ee11-11ea-860f-581ecb8e14d6.png)

This could be fixed by checking if the alias name provided matches an existing command.

**Steps to Reproduce**
1. Try to set an alias with the name of an existing command (e.g `glab alias set mr 'issue'`)
2. Command succeeds
3. Try to use the alias (e.g `glab mr`)
4. Behaviour is of the original command and not the alias.

**Your Environment**
* Version used: Latest commit of trunk (5716ba6a9eb67a4fb80ca899a01f3bde3f657606)
* Operating System and version: Arch Linux, kernel 5.8.5

**Comment by profclems** [comment]
Noted! I have added it to the v1.11.0 milestone

**Comment by profclems** [comment]
Pooled a quick fix with #199.
I believe there is still a more optimized solution that needs to be considered
