### ISSUE TITLE
check-update reports update, but version is the same

### ISSUE THREAD

**Issue by breml** [profclems/glab#217]
Version compare in `glab check-update` does report a new version even though, the installed and the latest version are the same.

**Description**

I have installed glab from the official .deb package (https://github.com/profclems/glab/releases/download/v1.10.0/glab_1.10.0_Linux_x86_64.deb). If I run `glab check-update`, I get the following output:

```none
A new version of glab has been released: 1.10.0 → v1.10.0
https://github.com/profclems/glab/releases/tag/v1.10.0
```

It looks like, because of the missing `v`, the two versions are considered different.

The output of `glab version` prints as follows:

```none
glab version 1.10.0 (08/25/2020)
git version 2.17.1
Made with ❤ by Clement Sam <clementsam75@gmail.com> and contributors
```

**Expected Behavior**

The two versions are the same, so there should be no not about a new version being available.

**Actual Behavior**

There is a version difference reported.

**Your Environment**

* Version used: 1.10.0
* Operating System and version: Linux

**Comment by profclems** [comment]
Thanks @breml for reporting this issue. 
This issue has been resolved by this e5fce4f1d308dcc85c78ea99506cca58a233311f and should work in newer releases. I'll do a release (v.1.11.0) this weekend
