### ISSUE TITLE
Issue Edit/Update

### ISSUE THREAD

**Issue by sunzoje** [profclems/glab#230]
**Is your feature request related to a problem? Please describe.**
Right now there's no way to update or edit issue for title, description, labels and others.

**Describe the solution you'd like**
Allow command to edit/update an issue:
`glab issue update <issue_no> --label <newlabel>` for adding label.
Likewise we can have `--unlabel <oldlabel>` to remove label

**Comment by profclems** [comment]
Thanks @sunzoje! This is worth considering
