### ISSUE TITLE
Error message for unresolved commands refers to invalid option `glab auth login` 

### ISSUE THREAD

**Issue by unjuli** [profclems/glab#237]
**Description**
For unresolved commands, the error message which is rendered is misleading since the command mentioned is invalid. 

**Expected Behavior**
```
$ glab mr create
none of the git remotes configured for this repository point to a known GitLab host. To tell glab about a new GitLab host, please use `glab config init`
```

**Actual Behavior**
```
$ glab mr create
none of the git remotes configured for this repository point to a known GitLab host. To tell glab about a new GitLab host, please use `glab auth login`
```

**Possible Fix**
Update the help text. 
(Happy to pick this up and push a fix.) 

**Steps to Reproduce**

1. Run any invalid glab commands like `glab mr list`, `glab mr create` without adding gitlab access tokens

**Context**
The help text is misleading since the command `glab auth login` is not available (at the moment).
Faced this issue while setting up the project locally.

**Your Environment**

* Version used: `glab v1.10.0-93-gf0feca7 (2020-10-01)`
* Operating System and version: `macOS 10.15.7`

**Comment by profclems** [comment]
Yeah I know I should've added this error message after the `glab auth login` command has been completed.
While working on this #229 I had wanted to add the login feature directly but I thought it would be wise to do that in a separate PR.

**Comment by profclems** [comment]
I don't know if we should depreciate the `glab config init` for `glab auth login` or leave it as an alternative for users who wouldn't want to login via `glab` but just create the access token and authenticate `glab` with it.
What are your thoughts?

**Comment by unjuli** [comment]
Yeah, it can be deprecated in future. Should be fine for now. 

By the way, I'm trying to test `glab config init` but it is not working for me. 

Using `glab` downloaded via Homebrew:
```
$ glab config init 
accepts 2 arg(s), received 0
```
Am I missing something?

**Comment by profclems** [comment]
I just fixed the auth check issue on the `config init` command. 
Also note that `glab` looks through the git remotes to find remote pointing to gitlab.com or any known host in the config.yml file. 
If your local repo does not point to any known/authenticated host, glab will throw an error.

Replying to your edit:
`config init` is not available in any of the released versions. https://github.com/profclems/glab/tree/v1.10.0#configuration

**Comment by unjuli** [comment]
Thanks for the clarification and quick fix.
Feel free to close the issue if needed.
