### ISSUE TITLE
Missing global flag option in glab config init

### ISSUE THREAD

**Issue by solidnerd** [profclems/glab#253]
**Description**

I installed glab fresh from homebrew and tried to set up a global configuration.

**Expected Behavior**

After `glab config init -g` a prompt appears to configure everything.

**Actual Behavior**

**Possible Fix**

**Steps to Reproduce**

1.  `glab config init -g`

**Context**

Can set a configuration globally like described in the [README.md](https://github.com/profclems/glab#configuration) 

**Your Environment**

* Version used: `glab 1.11.0-pre1 ()`
* Operating System and version: `Darwin Niclass-MBP.home 19.6.0 ... RELEASE_X86_64 x86_64`

**Comment by profclems** [comment]
Sorry for this... 
`glab config init` saves to the global configuration and does not have a global flag. I have updated the docs.
Thanks for reporting this Issue

**Comment by solidnerd** [comment]
You are welcome!  I wasn't sure if it's a bug so I didn't send the pr for fixing this.

**Comment by profclems** [comment]
I look forward to your PRs in case you'd want to submit one 😊. 
You started out a great work with [gogpat](https://github.com/solidnerd/gogpat)
