### ISSUE TITLE
NO_COLOR is not working

### ISSUE THREAD

**Issue by 34875634567** [profclems/glab#263]
Setting the env var `NO_COLOR` does not affect output 

**Expected Behavior**
Colour codes should not be present.
```bash
NO_COLOR=true glab mr list | grep '32m'
32m#244	integration-tests                                                     	(master) ← (integration-tests)
```

**Actual Behavior**
```bash
NO_COLOR=true glab mr list | grep '32m'
(no matches)
```

**Your Environment**

* Version used: 1.10.0
* Operating System and version: macOS Catalina

**Comment by profclems** [comment]
The `NO_COLOR` env var is recognized from v1.11.0-pre1. 
You should upgrade with `brew upgrade glab` if you used homebrew to install

**Comment by 34875634567** [comment]
Apologies, my mistake. Thanks for your help.
