### ISSUE TITLE
Unable to run on Linux CC7

### ISSUE THREAD

**Issue by vkuznet** [profclems/glab#272]
I downloaded glab from https://raw.githubusercontent.com/profclems/glab/trunk/scripts/quick_install.sh and install it in my local area, after that I get this
```sh
$ glab issue list
unexpected fault address 0x1002968
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x1002968 pc=0x726d36]

goroutine 1 [running, locked to thread]:
runtime.throw(0xd9940f, 0x5)
        /opt/hostedtoolcache/go/1.14.7/x64/src/runtime/panic.go:1116 +0x72 fp=0xc0001afdf0 sp=0xc0001afdc0 pc=0x432f72
runtime.sigpanic()
        /opt/hostedtoolcache/go/1.14.7/x64/src/runtime/signal_unix.go:692 +0x443 fp=0xc0001afe20 sp=0xc0001afdf0 pc=0x4490a3
github.com/yuin/goldmark/parser.init()
        /home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.2.0/parser/html_block.go:13 +0x96 fp=0xc0001afe98 sp=0xc0001afe20 pc=0x726d36
runtime.doInit(0x14e5340)
        /opt/hostedtoolcache/go/1.14.7/x64/src/runtime/proc.go:5420 +0x8a fp=0xc0001afec8 sp=0xc0001afe98 pc=0x44212a
runtime.doInit(0x14e3a00)
        /opt/hostedtoolcache/go/1.14.7/x64/src/runtime/proc.go:5415 +0x57 fp=0xc0001afef8 sp=0xc0001afec8 pc=0x4420f7
runtime.doInit(0x14e5a40)
        /opt/hostedtoolcache/go/1.14.7/x64/src/runtime/proc.go:5415 +0x57 fp=0xc0001aff28 sp=0xc0001afef8 pc=0x4420f7
runtime.doInit(0x14e53c0)
        /opt/hostedtoolcache/go/1.14.7/x64/src/runtime/proc.go:5415 +0x57 fp=0xc0001aff58 sp=0xc0001aff28 pc=0x4420f7
runtime.doInit(0x14e55c0)
        /opt/hostedtoolcache/go/1.14.7/x64/src/runtime/proc.go:5415 +0x57 fp=0xc0001aff88 sp=0xc0001aff58 pc=0x4420f7
runtime.main()
        /opt/hostedtoolcache/go/1.14.7/x64/src/runtime/proc.go:190 +0x1b6 fp=0xc0001affe0 sp=0xc0001aff88 pc=0x435596
runtime.goexit()
        /opt/hostedtoolcache/go/1.14.7/x64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0001affe8 sp=0xc0001affe0 pc=0x462e01
```
But glab help works just fine

**Description**
Unable to use executable

**Expected Behavior**

**Actual Behavior**

**Possible Fix**

**Steps to Reproduce**
1. glab issue list

**Context**

I also tried to build it from source but then I got stuck at this step
make
go build -trimpath -ldflags "-X main.build=2020-10-19  -X main.version=v1.11.0-pre2-19-g73b03fb -X main.debugMode=false" -o ./bin/glab github.com/profclems/glab/cmd/glab
go: github.com/lunixbochs/vtclean@v1.0.0: reading github.com/lunixbochs/vtclean/go.mod at revision v1.0.0: unknown revision v1.0.0

where we have
go version
go version go1.15.2 linux/amd64

**Your Environment**

glab version
glab version 1.10.0 (08/25/2020)
git version 1.8.3.1
Made with ❤ by Clement Sam <clementsam75@gmail.com> and contributors

uname -a
Linux vk-cc7.cern.ch 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

**Comment by profclems** [comment]
Sorry you're having this issue. I can't seem to reproduce the error. 
Can you upgrade to [v1.11.0-pre2](https://github.com/profclems/glab/releases/tag/v1.11.0-pre2) and see if you can reproduce the same error.
You can install with [snap](https://github.com/profclems/glab#snapcraft) or [Linuxbrew](https://github.com/profclems/glab#linuxbrew-homebrew)

**Comment by vkuznet** [comment]
Hi, this is quite old Linux distro and neither snap or Linuxbrew is installed. Instead, can you just provide a static executable to try out?

**Comment by profclems** [comment]
Check the releases page https://github.com/profclems/glab/releases/tag/v1.11.0-pre2 and download an rpm and install with yum.

You might as well install with:
```sh
$ wget https://github.com/profclems/glab/releases/download/v1.11.0-pre2/glab_1.11.0-pre2_Linux_x86_64.rpm

$ sudo rpm –i glab_1.11.0-pre2_Linux_x86_64.rpm
```

**Comment by vkuznet** [comment]
hmm, this seems to work as executable, and now I face yet another issue:
```
glab issue list
none of the git remotes configured for this repository points to a known GitLab host. Please use `glab config init` to configure a new host for glab
```
Then I did
```
glab config init
? Enter Gitlab Host (Current Value: gitlab.com):  gitlab.cern.ch
? Enter Gitlab Token:
✓ Configuration updated
```
but here I have no idea where to get the Token, so I just press Return. And, then
```
glab issue list
GET https://gitlab.cern.ch/api/v4/projects/cmsweb-k8s/services_config/issues: 404 {message: 404 Project Not Found}
```

When I look at my .git/config I see this
```
ssh://git@gitlab.cern.ch:7999/cmsweb-k8s/services_config.git
```

So, it seems to me, it is not that simple to use it with gitlab configured with custom authentication methods.

**Comment by profclems** [comment]
> but here I have no idea where to get the Token, so I just press Return. And, then

You should be able to get an access token with API scope at https://gitlab.cern.ch/profile/personal_access_tokens.

Do you access the API through a specific port?

**Comment by vkuznet** [comment]
Cool, it works now, thanks a lot for guidance.Since issue is resolved I'm closing it.
