### ISSUE TITLE
Ability to mark branch to be deleted on merge

### ISSUE THREAD

**Issue by zemzale** [profclems/glab#273]
**Is your feature request related to a problem? Please describe.**
When creating MRs from WebUI I always mark delete branch when merged, since I like to leave the repos clean with no stale branches. 

This is not possible right now, and it's quite frustrating UX since I can create MR, but to mark it to delete on merge I got to open the browser. 

**Describe the solution you'd like**
There are two places where I would like it enabled. 
First of all when creating MR I should be asked if I wanna mark this branch to be deleted. 
Also it would be nice if I can make this happen by an `update` command.
Some visual representation about that in `mr view` could be nice too. 

**Additional context**
This also could be said about squashing option. I personally don't use it, but if someone uses it the same applies to that option

**Comment by profclems** [comment]
Great! I thought of this too... gh has a similar implementation
You have spare time to take this up?

**Comment by zemzale** [comment]
Yeah, I probably will come up with an PR in the next couple of days

**Comment by profclems** [comment]
Squashing is enabled on the `mr merge` command via the `--squash-message` and `--squash` flags.
I'm thinking of adding an interactive way of doing this for interactive ttys if the `--squash` flag is not specified like this:

```sh
$ glab mr merge

? How do you want to merge it?
> Merge
 Squash and merge
 Squash, merge and delete source branch
 Merge and delete source branch
```
