### ISSUE TITLE
check-update failing

### ISSUE THREAD

**Issue by lionep** [profclems/glab#282]
When running check update, a new version is advertised, same as current one (v1.11.0)

**Description**

```
$ glab check-update
A new version of glab has been released: 1.11.0 → v1.11.0
https://github.com/profclems/glab/releases/tag/v1.11.0
```

**Expected Behavior**

No update should be proposed.

**Actual Behavior**

An update with same version is proposed.

**Possible Fix**

I think the heading "v" is responsible for this mismatch.

**Your Environment**

- glab v1.11.0d
- mac OS Catalina 10.15.7, installed with Homebrew.

**Comment by profclems** [comment]
Thanks @lionep. I actually thought I have fixed that
