### ISSUE TITLE
Bash completion broken

### ISSUE THREAD

**Issue by carlpett** [profclems/glab#287]
**Description**
The generated bash-completion is broken.

**Expected Behavior**
`glab <tab>` should complete.

**Actual Behavior**
`$ glab <tab>-bash: aliashash[""]: bad array subscript`

**Possible Fix**

**Steps to Reproduce**

1. `eval $(glab completion -s bash)`
2. `glab <tab>`

**Context**

**Your Environment**

* Version used: glab 1.11.0 (2020-10-26)
* Operating System and version: Fedora 33/Linux 5.8.15-301.fc33.x86_64 with GNU bash, version 5.0.17(1)

**Comment by profclems** [comment]
Resolved by @carlpett with #288. 
Thanks @carlpett
