### ISSUE TITLE
Repo search requires an undocumented positional argument, but does not seem to use it

### ISSUE THREAD

**Issue by jthornhill** [profclems/glab#295]
**Description**

`glab repo search` requires a positional argument. However, the function of the positional argument is not documented nor does it appear to do anything.

**Expected Behavior**

`repo search` should not require a positional argument

**Actual Behavior**

`repo search` requires a positional argument

**Possible Fix**

The search behavior should match the help text. If the argument is really used for anything, it should be documented, otherwise the requirement for it should be removed. Or, alternately, the currently also required `-s` argument could become a positional argument instead.

**Steps to Reproduce**

```
% glab repo search -s docker
accepts 1 arg(s), received 0
% glab repo search -s docker IGNOREME
Showing results for "docker"
˝  mygroup / myproj                                    0 stars 0 forks 0 issues  updated about 2 months ago
...
```

**Context**
I attempted to use repo search

**Your Environment**
Arch linux, AUR version 1.11.1 (binary download from releases page)

**Comment by zemzale** [comment]
This seems to be an error with the repo search command. It for some reason requires one argument that it doesn't use. I opened a PR to fix this.
