### ISSUE TITLE
Copy labels when creating MR for issue

### ISSUE THREAD

**Issue by debdolph** [profclems/glab#299]
It would be nice if glab would copy the labels of an issue when creating a mr with `glab mr for $issue`. This option maybe could be configurable with a command argument.

**Comment by zemzale** [comment]
This seems like a good feature to add.

I would propose we add option `--wtih-labels` for `mr for` command that would copy the labels from the related issue on creation.

**Comment by profclems** [comment]
I agree with the `--with-label` flag option
