### ISSUE TITLE
add pipelines support (ex. list, status ,delete)

### ISSUE THREAD

**Issue by abakermi** [profclems/glab#30]
**Is your feature request related to a problem? Please describe.**
CI pipelines are cores features for GitLab, we should add support for that ex.deleting, listing

**Describe the solution you'd like**
add a command for  minimum & easy functionality

`glab pipeline  [list, status,delete]`

**Describe alternatives you've considered**
`glab pipe  [list, status,delete]`

**Comment by abakermi** [comment]
@profclems I can help with that

**Comment by profclems** [comment]
I marked it as relevant so you can open a PR

**Comment by profclems** [comment]
> @profclems I can help with that, PR

I marked it as relevant so you can open a PR

**Comment by profclems** [comment]
@abakermi I hope you share so we get more users and contributors
