### ISSUE TITLE
Table printer should take as much terminal space as it can

### ISSUE THREAD

**Issue by zemzale** [profclems/glab#300]
**Is your feature request related to a problem? Please describe.**
When we are printing something with table printer we always default width of 70 cells. When we have long output like for example in #106, this output gets cut off while the terminal has still plenty of output space.

**Describe the solution you'd like**
We should query the terminal for it's width. There is https://godoc.org/golang.org/x/crypto/ssh/terminal#GetSize function from the terminal library. I have used it for one of my own helper programs, but have not tested how good it works on other OSes then Linux. 

**Describe alternatives you've considered**
If querying terminal for it's size is not possible we could just allow user set their own terminal size somehow.

**Comment by profclems** [comment]
Resolved by this commit 7506a8a837812a9a0fd0ea12d6d4ae7b55b3649e
