### ISSUE TITLE
Running `glab config init` the pasted in token isn't masked in the terminal, when using `glab auth login --hostname` it is

### ISSUE THREAD

**Issue by espoelstra** [profclems/glab#311]
**Description**
Pasted token not masked in all cases.

**Expected Behavior**
Pasted token should be masked.

**Actual Behavior**
Pasted token appears inline after the prompt.

**Steps to Reproduce**

1. `glab config init`
2. Set custom hostname
3. Paste token at the prompt
4. Observe token in the scrollback/visible output.

**Context**

This is unsafe if the output of the terminal is being logged somewhere. A workaround might be to redirect in from a file, but that isn't always possible and is unfriendly to inexperienced users and prone to error.

**Your Environment**

* Version used: 1.11.1
* Operating System and version: Debian Buster (10.6)

**Comment by profclems** [comment]
`glab config init` is set to be depreciated in favour of `glab auth login`.

Passwords are masked when using `glab auth login`.

`glab auth login` has `--stdin` option which allows to read token from file
https://github.com/profclems/glab#authentication
