### ISSUE TITLE
Tests fail with `make test`

### ISSUE THREAD

**Issue by guyfedwards** [profclems/glab#313]
**Description**

Currently the tests are failing seemingly due to some explicit checking of `profclems/glab` for remotes in tests and also some tests for creating merge_requests failing to push changes. Looking through the code it seems as though for the tests there shouldn't be any code actually running against the main repo, should be using the `test/testdata` setup so could be a config/my env issue.

Also worth noting is that you cannot run the tests if you have cloned the repository outside of `$GOPATH/src/github.com/profclems/glab` as the setup for mock repo use the hardcoded path.

**Expected Behavior**

Anyone should be able to run the tests and they should all pass.  
Ideally should support go modules, but if not something in the docs to say running tests must be at specific path. 

**Actual Behavior**

**Possible Fix**

`cmdhelper.CopyTestRepo` could probably just use the directory the test command is being called from (`make test` is always called from root), or take an explicit environment variable

**Steps to Reproduce**

1.run `make test` from non-GOPATH location || run `make test` with a different remote url for origin

**Context**

trying to run the tests

**Your Environment**

* Version used: trunk
* Operating System and version: Linux archlinux 5.9.6-arch1-1

**Comment by profclems** [comment]
Thanks @guyfedwards for the detailed input. This PR (#317) should fix it
