### ISSUE TITLE
[Feature] Delete Repository

### ISSUE THREAD

**Issue by eingress** [profclems/glab#318]
Please implement

DELETE https://gitlab.com/api/v4/projects/<REPOSITORY>

**Comment by profclems** [comment]
Thanks @eingress. I initially thought of adding this feature but held back looking at how critical it is and the problems it could create; such as a user mistakenly deleting a repo.
But I think we can implement it to be safe following these:

- user should be prompted to confirm action:
   - ask to verify repo name (as implemented on the UI)
   - a 'YES/NO' confirmation prompt

- add `--force, -f` flag to avoid being prompted

**Comment by eingress** [comment]
With great power comes great responsibility…

A force flag would be preferable, one of the reasons to have this in a cli is to avoid jumping through the hoops the Web UI entails.

Use case, multi-repo (opposed to mono-repo) projects; I want to shell script/loop the deletion of several repos at once, being forced to click through multiple dialogues is painful at best.

[hub](https://github.com/github/hub ) allows this:

`hub delete -y <repository>`
