### ISSUE TITLE
Pass variables when running a pipeline

### ISSUE THREAD

**Issue by junderhill** [profclems/glab#319]
When running pipelines we use variables to trigger a release to the specified environment.

An additional argument when calling `glab pipeline run` such as `--variables KEY:VALUE` would be ideal.

Currently, the only alternative is to use the web UI.

**Comment by junderhill** [comment]
I have just noticed looking at the code there is already a mention of this functionality in a `todo` comment.

https://github.com/profclems/glab/blob/9b0868068e88acdec171aa07d6651df537b72986/commands/pipeline/run/pipeline_run.go#L60

I don't have much experience in `Go` but I will try and take a look at implementing this functionality over the next day or so.

**Comment by profclems** [comment]
> I don't have much experience in `Go` but I will try and take a look at implementing this functionality over the next day or so.

Thanks @junderhill. I look forward to that
