### ISSUE TITLE
Include more details in `glab mr view`

### ISSUE THREAD

**Issue by elkowar** [profclems/glab#322]
**Is your feature request related to a problem? Please describe.**
Currently, when looking at merge requests from glab, relevant details like if a merge request has been approved, the pipeline-status, or if it can be merged directly (rebase necessary?) are not easily visible.

**Describe the solution you'd like**
More details should be included in top status line. Here, it already mentions "merged" if a PR has been merged, so adding more details there would fit perfectly.
Additionally, it might be useful to include information about approval and pipeline-status in the `mr list` command, too.

**Comment by zemzale** [comment]
I am for adding more info to the `mr view` command. 

Pipeline statues would be pretty easy to implement I suppose, but that should probably be just overview t.i. pipelines still running/failed/success. Smaller details should be gotten from `pipeline` commands. 

For approval statuses there is the problem that anything that is related to [approvals](https://docs.gitlab.com/ee/api/merge_request_approvals.html) is under starter/bronze plans, but it can be implemented in a way that these things show up only when they are available.

Merge status is available from the API under `merge_status` field. We could just display that, and the user should have a clear vision what he can do with the merge request.

I am open to mock up a PR for this in the next week if these changes make sense.

**Comment by profclems** [comment]
Yeah should be easier adding the pipeline status should be straightforward since the single mr endpoint (GET) comes with the pipeline details as well.
The merge details as @elkowar suggested can also be added.
```json
{
...
"pipeline": {
    "id": 29626725,
    "sha": "2be7ddb704c7b6b83732fdd5b9f09d5a397b5f8f",
    "ref": "patch-28",
    "status": "success",
    "web_url": "https://gitlab.example.com/my-group/my-project/pipelines/29626725"
  },
...
"merged_by": {
    "id": 87854,
    "name": "Douwe Maan",
    "username": "DouweM",
    "state": "active",
    "avatar_url": "https://gitlab.example.com/uploads/-/system/user/avatar/87854/avatar.png",
    "web_url": "https://gitlab.com/DouweM"
  },
...
}
```
https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr
