### ISSUE TITLE
Alpine Linux Packaging

### ISSUE THREAD

**Issue by profclems** [profclems/glab#331]
Most CI environments like to use alpine Linux for its lightweight nature.
It would be nice to have `glab` packaged in the official alpine package repository so it can be installed with:
```sh
$ apk add glab
```
In the meantime, you can easily install with the [quick install script](https://github.com/profclems/glab/blob/trunk/scripts/quick_install.sh) via curl or wget as stated in the [readme](https://github.com/profclems/glab#quick-install-bash)
```
$ curl -sL https://j.mp/glab-i | sudo bash
```
I would like to do it but I'm no alpine packaging expert 🤗. 
It is however, open for anyone who would like to help with the packaging

**Comment by solidnerd** [comment]
Hey @profclems, 
I want to help here and also learn how to build an alpine package. I'll have a look at the Weekend.

Some Information:
- [APKBUILD example](https://wiki.alpinelinux.org/wiki/APKBUILD_examples:Simple)
- [Abuild](https://wiki.alpinelinux.org/wiki/Abuild_and_Helpers)

**Comment by profclems** [comment]
Thanks a lot @solidnerd. I will be looking forward to that

**Comment by solidnerd** [comment]
@profclems Can you assign me the ticket ;)

**Comment by profclems** [comment]
@solidnerd, here's the alpine aport repository where you can submit the package build file (APKBUILD) https://gitlab.alpinelinux.org/alpine/aports

**Comment by solidnerd** [comment]
Hey @profclems,
I started to submit the package in https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/16051 . I hope this will be merged afterwards it will be instable directly in the image.
