### ISSUE TITLE
Enable issue linking for issue creation

### ISSUE THREAD

**Issue by mimor** [profclems/glab#351]
We can link MR's to an issue, but we are not able to link related issues through the cli.

### The current flow is:
* create an issue `glab issue create --title "" --description ""` 
* go to the web-interface to link the relevant issue.

### Possible solution:
Introduce a --linked-issue flag, that takes an issue ulr/id from the cli.

**Comment by profclems** [comment]
Thanks @mimor for your suggestion. 
We are very careful implementing features that are ***limited*** by GitLab tiers and ***newer***.

`glab` relies heavily on the GitLab API and it seems the [Issues Link API](https://docs.gitlab.com/ce/api/issue_links.html#create-an-issue-link) falls into the two categories I have mentioned.

> The simple “relates to” relationship moved to GitLab Core in 13.4.

We may however, consider this one since  it is now supported for ***GitLab.com Free***. My only concern is it being new for ***GitLab Core*** users.

**Comment by profclems** [comment]
While you wait as we work on this, you can easily implement this with the `glab api` command as it helps you interact with the GitLab API directly.
```sh
glab api /projects/<PROJECT_ID_OR_PATH>/issues/1/links -X POST -F target_project_id=<PROJECT_ID_OR_PATH> -F target_issue_iid=<TARGET_ISSUE_ID>
```
Here is an example:
```sh
glab api /projects/glab-cli%2Ftest/issues/1/links -X POST -F target_project_id=glab-cli/test -F target_issue_iid=2
```
You can set a short alias for this command with:
```sh
glab alias set linkIssue 'api /projects/$1/issues/$2/links -X POST -F target_project_id=$1 -F target_issue_iid=$3'
```
and now you should be able to use `glab linkIssue` command like:
```sh
glab linkIssue <PROJECT_ID_OR_PATH> <ISSUE_ID> <TARGET_ISSUE_ID>
```
Example:
```sh
glab linkIssue glab-cli%2Ftest 1 2
```

`glab` is highly customizable so you can use it whichever way you want it.

**Comment by mimor** [comment]
I'd like to complement you on this awesome and complete response 👏

**Comment by wwalker** [comment]
@profclems Thank you for a great program!!

Slight correction to help others wanting to link issues.

This doesn't work for me:
```
glab alias set linkIssue 'api /projects/$1/issues/$2/links -X POST -F target_project_id=$1 -F target_issue_iid=$3'
glab linkIssue glab-cli%2Ftest 1 2
```
However, this does, because, in the uri path, you need `%2F` (url-encoded `/`) but in the `target_project_id` you need `/`:
```
glab alias set linkIssue 'api /projects/$1%2F$2/issues/$3/links -X POST -F target_project_id=$1/$2 -F target_issue_iid=$4'
glab linkIssue glab-cli test 1 2
```
