### ISSUE TITLE
MR use user names for `mr create` assignee flag 

### ISSUE THREAD

**Issue by zemzale** [profclems/glab#358]
**Is your feature request related to a problem? Please describe.**
When creating mr using `--assignee` flag it expects the User ID as in the number `id`.
This is not really user friendly since I am not a robot and it's hard for me to remember even my own numeric ID, let alone other peoples.
We could change this to behave just like in `mr update` where we expect the user name, instead of the ID.

For that matter we could change this in `issue create` too, and maybe some other place that I am missing.

Optionally I think we should fail if the assignee is not found, because there is no indication to the user that he used the wrong assignee ID/name and the MR didn't get assigned. I had done this a few times, with thinking that MR is assigned to someone for review when in reality it no assignes. 

**Describe the solution you'd like**
1. Expect username to be passed to `--assignee`
2. Fetch the user from API by it's username and use that ID to in MR creation 
3. (maybe) Fail if the user is not found

**Comment by profclems** [comment]
This makes perfect sense.
I actually expected this to be brought up. I was trying to make `glab` quite straightforward and simple initially.

I agree with the solution you've suggested since we already have this https://github.com/profclems/glab/blob/e0f23771966d566bb318af6034fa5511afe869c1/pkg/api/user.go#L20-L38

**Comment by zemzale** [comment]
Then if you agree on this I will implement sometime in next few days

**Comment by zemzale** [comment]
Resolved by #361
