### ISSUE TITLE
Allow "me" as an alias for current user when specifying a user name

### ISSUE THREAD

**Issue by nfriend** [profclems/glab#362]
**Is your feature request related to a problem? Please describe.**

Not a problem! Just a small UX improvement opportunity.

To get a list of all MRs assigned to me, I can run this:

```
glab mr list --assignee nfriend
```

**Describe the solution you'd like**

It would be neat if I could instead do:

```
glab mr list --assignee me
```

**Additional context**

This would be consistent with [GitLab's quick actions](https://docs.gitlab.com/ee/user/project/quick_actions.html#quick-actions-for-issues-merge-requests-and-epics), for example:

```
/assign me
```

**Comment by nfriend** [comment]
Wait, just read the docs a little closer and noticed there's a `--mine` flag 🤦 . This is even better than my proposed solution! Closing 👍

**Comment by profclems** [comment]
Great! 

Also note that with the `glab api` and `glab alias` commands, you can easily create custom commands if they're not already available in glab.
Check the example in this comment https://github.com/profclems/glab/issues/351#issuecomment-738758591
