### ISSUE TITLE
Use 'ci' as alias to 'pipeline' and deprecate 'pipeline ci'

### ISSUE THREAD

**Issue by profclems** [profclems/glab#372]
**Describe the feature or problem you'd like to solve**
Currently, `glab` has `ci` as a subcommand under `pipeline` which is run as `glab pipeline ci <subcommand>`.
Having a lot of nested subcommands introduces a lot of complexities and becomes difficult to master the tool. 

`glab` should have a well-defined standard format which is expected to be `glab <noun> <verb> [flags]`

**Propose a Solution**
The nested `pipeline ci` command should be deprecated and all the commands under it (`lint`, `trace`, `view`) should be added to the `pipeline` command. 

`ci` should then be used as an alias to `pipeline`.

For backward compatibility, the `pipeline ci` command must not be completely removed; it should execute and warn the user to switch to `ci`.

**Additional context**
`ci pipeline` makes more sense than the inverse `pipeline ci`.

This issue is open for discussion in order to take the right decision

**Comment by zemzale** [comment]
I am totally in support of this. The `pipeline ci` command is confusing, and just bringing it all under `pipeline` command would be better.
