### ISSUE TITLE
double default statement in glab mr merge --help

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#382]
**Description**
Double default statement on --when-pipeline-succeeds, see screenshot (first is fixed build and second is current build)

![image](https://user-images.githubusercontent.com/30738253/102840393-8865af00-43e1-11eb-982b-747ed36001b2.png)

**Expected Behavior vs Actual Behavior**
Only one default should appear

**Possible Fix**
#381 

**Steps to Reproduce**
1. glab mr merge --help

**Your Environment**

* Version used (Run `glab --version`):  glab version 1.12.1-82-g0c3ff7e (2020-12-21)
* Operating System and version: Fedora SilverBlue 33 GNOME

**Comment by profclems** [comment]
Resolved with #381
