### ISSUE TITLE
glab asks which repository when multiple remotes are present but uses 'origin' repository anyway

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#385]
**Description**
Screenshot should explain it all, It asks if I want Leo/aports or alpine/aports, I pick the latter but the mr view command still uses the old one.

![image](https://user-images.githubusercontent.com/30738253/102844152-8c95ca80-43e9-11eb-8c72-0473e3bcc92a.png)

**Expected Behavior vs Actual Behavior**
It to check against the picked repo after asking me a repo to pick

**Steps to Reproduce**
1. Clone a gitlab repo from gitlab.alpinelinux.org like gitlab.alpinelinux.org/Leo/atools
2. Add a second remote
3. try to run any command querying a merge request/issue
4. when it asks which one you want to query in by default answer the one that isn't origin
5. watch it use the one that is origin

**Your Environment**

* Version used (Run `glab --version`): glab version 1.12.1-82-g0c3ff7e (2020-12-21)
* Operating System and version: Fedora SilverBlue 33

**Comment by maxice8** [comment]
I can confirm if I rename my `origin` to `upstream` and my `upstream` to `origin`it "works" by using `origin`

**Comment by profclems** [comment]
I am unable to reproduce this error.

Run `git config -l | grep glab-resolved` and see if it shows either `remote.upstream.glab-resolved=base` or `remote.origin.glab-resolved=base`

**Comment by maxice8** [comment]
![image](https://user-images.githubusercontent.com/30738253/102848125-ca4b2100-43f2-11eb-8582-020f998764d8.png)

**Comment by maxice8** [comment]
Yes I removed the line from .git/config, before running everything again

**Comment by maxice8** [comment]
Will be fixed by #394, glab got bit by pointers and their fun!
