### ISSUE TITLE
glab tells it has merged even though it might fail

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#386]
**Description**
At alpine/aports we forbid any merge commits and all branches must be rebased, So if glab set one merge request to be merged when pipeline succeeds it might not be merged if another is merged in the meantime.

![image](https://user-images.githubusercontent.com/30738253/102848900-b4d6f680-43f4-11eb-888b-ed5703c4ec0f.png)

**Expected Behavior vs Actual Behavior**
It to tell me it has been set to be merged when the pipeline succeed as it is possible this message is misleading

**Possible Fix**
#387 

**Steps to Reproduce**
1. glab mr merge <num>

**Your Environment**

* Version used (Run `glab --version`): glab version 1.12.1-82-g0c3ff7e (2020-12-21)
* Operating System and version: Fedora SilverBlue 33

**Comment by maxice8** [comment]
Created #387

**Comment by profclems** [comment]
Makes complete sense. The message can be misleading.

Thanks for the PR. I will review right away
