### ISSUE TITLE
mr create doesn't respect -R

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#388]
**Description**
Passing `-R gitlab.alpinelinux.org/alpine/aports` does not dissuade `glab` from creating it against the same repo.

![image](https://user-images.githubusercontent.com/30738253/102857454-3768b180-4407-11eb-9fc6-305b910b8836.png)

**Expected Behavior vs Actual Behavior**
Expected for it to create against alpine/aports

**Steps to Reproduce**
1. Try to create a merge request that aims at another target

**Your Environment**

* Version used (Run `glab --version`): glab version 1.12.1-82-g0c3ff7e (2020-12-22)
* Operating System and version: Fedora SilverBlue 33

**Comment by profclems** [comment]
This is resolved in #410
