### ISSUE TITLE
when creating mr, have an equivalent to glab-resolved to set a default target project.

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#393]
**Describe the feature or problem you'd like to solve**
When contributing to a repository that isn't yours it is hard to use the `--target-project` switch as it requires knowing the ID and using it every time.

**Propose a Solution**
Create a `glab-targeted` entry that acts the same way `glab-resolved` is used but use it when deciding which TargetProjectID to use.

**Additional context**
Here is a crude workflow graph I made

![image](https://user-images.githubusercontent.com/30738253/103015122-a2f17280-451e-11eb-8189-c5a7d2864364.png)

**Comment by maxice8** [comment]
Thinking more about it I think we will need a third glab-.

**Comment by profclems** [comment]
Great suggestion. The workflow makes sense. 
Aside from setting the `glab-targetted`, we should consider accepting a string for the `--target-project` so the user can specify the repo name `--target-project OWNER/REPO` which will be converted to the ID. 

If the flag is specified, it should override the `glab-targetted`.

**Comment by profclems** [comment]
> Thinking more about it I think we will need a third glab-.

What will that be?

**Comment by maxice8** [comment]
Because glab-resolved should be used only for querying issues, one also needs a glab-based and a glab-targeted.

glab-resolved -> decides which project to look for issues and Merge Requests, think `glab issue view` and `glab mr list`
glab-based -> decides which project to push your local branch and from where you create your merge request
gitlab-targeted -> decides which project the merge request must be made against

If you are developing your own project then all 3 of them are the same, if you are an external contributor then:

gitlab-resolved -> upstream (they have the issues and merge requests)
gitlab-based -> origin (you only have permissions to push and create merge requests in your fork)
gitlab-targeted -> upstream (you want your changes upstream)

**Comment by maxice8** [comment]
> Great suggestion. The workflow makes sense.
> Aside from setting the `glab-targetted`, we should consider accepting a string for the `--target-project` so the user can specify the repo name `--target-project OWNER/REPO` which will be converted to the ID.
> 
> If the flag is specified, it should override the `glab-targetted`.

I'll update the graph

**Comment by profclems** [comment]
> Because glab-resolved should be used only for querying issues, one also needs a glab-based and a glab-targeted.
> 
> glab-resolved -> decides which project to look for issues and Merge Requests, think `glab issue view` and `glab mr list`
> glab-based -> decides which project to push your local branch and from where you create your merge request
> gitlab-targeted -> decides which project the merge request must be made against
> 
> If you are developing your own project then all 3 of them are the same, if you are an external contributor then:
> 
> gitlab-resolved -> upstream (they have the issues and merge requests)
> gitlab-based -> origin (you only have permissions to push and create merge requests in your fork)
> gitlab-targeted -> upstream (you want your changes upstream)

Great. `gh` has a way of asking the user which repo to push the commit when creating a merge request. If I get you well, the `glab-based` fits that purpose. 
I think that will be useful for non-ttys but for ttys prompting the user where to push to should help.

We should also take into consideration, situations where prompts are disabled by the user.

**Comment by maxice8** [comment]
Yes, that is exactly the purpose of `glab-based`, we ask the user which repo they want to push and store it there until they decide they want another.

We might be able to get away with only 2 if we assume `glab-resolved` is always set to the `upstream` repository (if it is applicable)

**Comment by profclems** [comment]
Nice. I just thought about this: `glab` provides no way to remove the values stored in the git config unless the user removes it from the .git/config themselves.

I think we should consider that too so `glab-resolved`, `glab-based` and `glab-targetted` can be removed. 

`glab-based` value should also be overridable via a Persistent Flag just like the `glab-resolved` is overridable by the `--repo` flag.

**Comment by profclems** [comment]
It's been 21days since our last release. We are supposed to do a minor release today (v1.13.0). 

We've got a load of stuff [pending release](https://github.com/profclems/glab/projects/1#column-11177289)

**Comment by maxice8** [comment]
This certainly can come later it is a rather major change

**Comment by maxice8** [comment]
I started working on this and it is all very intertwined, it will take a while, I expect this to arrive in a few weeks

**Comment by profclems** [comment]
Yeah I actually expect it to be that complex. It took a while when working on the `glab-resolved`

**Comment by maxice8** [comment]
I'm thinking of using  a simpler scheme with 2 `glab-resolved` one that is `glab-resolved = base` and `glab-resolved = head` the base is used for finding the target project and is the same as before and the new one, `head`, is where one pushes changes.

So if you are working on your project:

`head`->`profclems/glab`
`base`->`profclems/glab`

If you're working on a fork

`head`->`profclems/glab`
`base`->`upstream/glab`

**Comment by maxice8** [comment]
`--target-project` would be back to using only `int` and `-R` would be used instead to find the target project

**Comment by profclems** [comment]
> I'm thinking of using a simpler scheme with 2 `glab-resolved` one that is `glab-resolved = base` and `glab-resolved = head` the base is used for finding the target project and is the same as before and the new one, `head`, is where one pushes changes.
> 
> So if you are working on your project:
> 
> `head`->`profclems/glab`
> `base`->`profclems/glab`
> 
> If you're working on a fork
> 
> `head`->`profclems/glab`
> `base`->`upstream/glab`

Interesting how I was typing a similar suggestion!

**Comment by profclems** [comment]
But the user should be prompted to select the `head`. There could be a case where the repo is a fork but a standalone project so the user might still use it as both `head` and `base`
For non-ttys, the `head` should be the fork by default

**Comment by maxice8** [comment]
Absolutely, choosing `base` and `head` will work the same way except support for choosing `head` is only done when using `mr create` instead of any command like `issue view`, `mr list`, etc

**Comment by profclems** [comment]
Sounds good

**Comment by maxice8** [comment]
fixed by #410, it is not exactly what is discussed here **initially** but it is what it was agreed upon.
