### ISSUE TITLE
Allow 'issue' and 'mr' update to unlock discussion

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#400]
**Describe the feature or problem you'd like to solve**
There is currently no way to unlock a previously locked discussion, there is `--lock-discussion` but no equivalent for unlocking it.

**Propose a Solution**
Add a `--unlock-discussion` flag to `mr update` and `issue update`

**Comment by maxice8** [comment]
If a yes is give I'll work on it

**Comment by profclems** [comment]
Nice. You can go ahead.

I was also thinking of using the `--lock-discussion`. If set to false, unlocks the discussion.
But looking much into it, adding `--unlock-discussion` is expressive but both shouldn't be used at the same time
