### ISSUE TITLE
Add command to create a To Do for a merge request

### ISSUE THREAD

**Issue by profclems** [profclems/glab#41]
**Is your feature request related to a problem? Please describe.**
User should be able to create a ToDo for a merge request

**Describe the solution you'd like**
`glab mr <merge-id> new-todo`

**Describe alternatives you've considered**
`glab mr <merge-id> create-todo`
`glab mr <merge-id> todo create`
`glab mr <merge-id> todo new`

**Additional context**
https://docs.gitlab.com/ee/api/merge_requests.html#create-a-todo

**Comment by pgollangi** [comment]
Hey @profclems since TODO is just marking MR, i would go with `glab mr todo <merge-request-id>`. What do you think?

**Comment by profclems** [comment]
Yeah I think it's great. 
It will be consistent since note uses `glab mr note <merge-request-id>` so I agree with you on `glab mr todo <merge-request-id>` 👍
