### ISSUE TITLE
Ability to get user contribution events

### ISSUE THREAD

**Issue by profclems** [profclems/glab#42]
**Is your feature request related to a problem? Please describe.**
There should be a command to get the contribution events for the specified user, sorted from newest to oldest. 

**Describe the solution you'd like**
`glab user events`

**Describe alternatives you've considered**
`glab user contributions`

**Additional context**
https://docs.gitlab.com/ee/api/events.html#get-user-contribution-events

**Comment by zemzale** [comment]
I added a Draft PR for this feature. Would be nice if I could get some input
