### ISSUE TITLE
More interactive options while creating issue/mr

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#439]
**Describe the feature or problem you'd like to solve**

While creating an issue it would be nicer if we could also set assignees and milestone as we can with the flags

**Propose a Solution**

Prompt the user for adding assignees and milestone just like it is done with labels, for assignees we can list all the users and pick them.

**Comment by profclems** [comment]
I thought of this too, not only for `issue create` but `mr create` as well.

**Comment by maxice8** [comment]
with #446 and #453 all things that can be passed via `--flag` are now supported, except for boolean or uncommon stuff like `--weight`, `--confidential`, `--wip`
