### ISSUE TITLE
Support `OWNER:branch` for querying Merge Requests

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#440]
**Describe the feature or problem you'd like to solve**

Sometimes it is nicer to checkout/view Merge Requests by using the branch name instead of its Internal-id

**Propose a Solution**

modify `MRFromArgsWithOpts` in `commands/mr/mrutils/mrutils.go` to:

See workflow chart below:

**Additional context**

![image](https://user-images.githubusercontent.com/30738253/103248981-e4818380-494b-11eb-8929-15b8a7495600.png)

**Comment by maxice8** [comment]
For note, `github-cli` also does this

**Comment by profclems** [comment]
Nice one! 

`glab` already supports specifying a branch but errs if there are multiple merge requests with the same branch name from different repos (fork)

   - MR `#1` with head `user1:master`
   - MR `#2` with head `user2:master`

`glab` only returns the first `open` MR for that branch specified. 
https://github.com/profclems/glab/blob/ce03a68b7ce4aed8f7e63fa440402076701f7be2/commands/mr/mrutils/mrutils.go#L231
With that, I agree with prompting the user to select from the matches. 

It will also be handy to be able to specify `user:branch-name` as you've proposed.

The workflow chart covers all cases 👍
