### ISSUE TITLE
Add command to clone repository

### ISSUE THREAD

**Issue by profclems** [profclems/glab#45]
**Is your feature request related to a problem? Please describe.**
User should be able to clone a GitLab repo with a clear and concise command in `glab`

**Describe the solution you'd like**
`glab clone owner/repo`
Eg. `glab clone profclems/glab`

**Comment by abakermi** [comment]
@profclems I will handle that

**Comment by profclems** [comment]
Great!

**Comment by abakermi** [comment]
@profclems would you prefer cloning the repos using the file archive (gitlab API)  endpoint or using external command git
`git clone https://gitlab.com:<personal_access_token>@gitlab.com/user/repo.git'`

**Comment by abakermi** [comment]
currently , I have the zip file with the latest commit sha and option to specify the format `--format`,
should we extract the zip to a directory ?
![screenshot](https://user-images.githubusercontent.com/60294727/89661780-c99a6e00-d8db-11ea-8bf0-9fa3ebb8d61a.gif)

**Comment by profclems** [comment]
Great! 
I think using the file archive endpoint is great for getting the zip format but with cloning the repo files into a folder, executing an external git command will be great. GLab depends on git anyway. .What do you think?

**Comment by abakermi** [comment]
I think clone **without options** will launch external `git clone` command and with options like the` --format `we will just download the stream archive

**Comment by spiderkeys** [comment]
One thing that would be super helpful, as some extra bells and whistles to this feature, especially for individuals/companies that have a large number of repos, is the ability to run a single command that can clone an entire Gitlab group (including its subgroups) to your machine with the same group/subgroup structure. 

I hacked together a python script for this a while back, but it seems like someone else has made a proper tool for it recently:
https://github.com/ezbz/gitlabber

Maybe this could be leveraged to bring the same features into glab?

**Comment by profclems** [comment]
@spiderkeys that's being considered. Thanks!
Do you think you could open a quick PR to help speed up with that?

**Comment by abakermi** [comment]
@spiderkeys that would be a huge recursive way, the `clone` command should only clone a single repo with `options` just like git does

**Comment by profclems** [comment]
@abakermi, how about a flag that allows a user to specify the repo to clone like:
```sh
glab repo clone --repo=OWNER/REPO
```
Alternatives
```sh
glab clone OWNER/REPO
```
Or 
```sh
glab repo clone OWNER/REPO

**Comment by abakermi** [comment]
@profclems great with that, I will send PR tomorrow
