### ISSUE TITLE
be more descriptive of what is done when updating an issue/mr

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#461]
**Describe the feature or problem you'd like to solve**

When updating an issue or merge request with `issue update` or `mr update` it would be nicer if we told the user what exactly was done.

**Propose a Solution**

Instead of a blank `Updated` a `changed title to FOO` or `made confidential`. for long things like descriptions I think we can get away with `updated description` but for short things like locking/unlocking a discussion we can affort to say `locked discussion on $ISSUE`

**Additional context**

This is done in gh and help re-assure the user that it didn't mess up anything, nothing worse than doing X and then finding out actually it was Y that happened!

**Comment by profclems** [comment]
@maxice8 Thanks, that's a good idea.

**Comment by profclems** [comment]
I'm thinking of how best we could bind the message to the flag.

Also, what happens if there are more edits done in the update like `glab mr update -t "New Title" --unlock-discussion`?
It's either we just print "Updated issue" or have multiple messages printed for each action taken

```sh
$ glab mr update -t "New Title" --unlock-discussion --ready --assignees profclems
- Updating issue
✓ changed title to FOO
✓ unlocked discussion
✓ marked as ready for review
✓ assigned @profclems 
...
```

**Comment by maxice8** [comment]
> typing from phone

I'm thinking have an Updates []string that is appended with each flag used and printed item per line at the end

**Comment by maxice8** [comment]
I'll make a prototype tomorrow (2 AM here)

**Comment by profclems** [comment]
> I'm thinking have an Updates []string that is appended with each flag used and printed item per line at the end

Sounds good
