### ISSUE TITLE
make assignment on mr create more friendly

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#468]
**Describe the feature or problem you'd like to solve**

Make assignment of users on `mr create` more friendly by acquiring a List of all users that can merge to the repository and then presenting it as a multiprompt.

**Propose a Solution**

See above.

**Comment by profclems** [comment]
For this, we would have to use the [Member API](https://docs.gitlab.com/ee/api/members.html) to get the list of members for the project

https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-members

We may have to consider the access levels so we don't include guests and users with low access levels

**Comment by maxice8** [comment]
This is the one that should be closed by #520
