### ISSUE TITLE
Fix spelling mistakes in the README md file

### ISSUE THREAD

**Issue by lwpamihiranga** [profclems/glab#47]
Found some spelling mistakes in the README file

https://github.com/profclems/glab/blob/trunk/README.md

**Comment by profclems** [comment]
@lwpamihiranga thanks for the issue :)
Do you think you can submit a quick PR for this?

**Comment by lwpamihiranga** [comment]
> @lwpamihiranga thanks for the issue :)
> Do you think you can submit a quick PR for this?

Already did 😉
