### ISSUE TITLE
deb file has incorrect file paths

### ISSUE THREAD

**Issue by lila** [profclems/glab#508]
**Description**
installing the deb package on linux installs the glab executable in the incorrect location.  It installs in `/usr/local/bin/bin/`, but should be `/usr/local/bin`

**Expected Behavior vs Actual Behavior**
should be installed in `/usr/local/bin`

**Possible Fix**

**Steps to Reproduce**
`~$` dpkg -c ./glab_1.13.1_Linux_x86_64.deb 
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/local/
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/local/bin/
drwxr-xr-x 0/0               0 2020-12-28 17:22 ./usr/local/bin/bin/
-rwxr-xr-x 0/0        19165184 2020-12-28 17:22 ./usr/local/bin/bin/glab`

**Comment by zemzale** [comment]
Thanks for reporting this. I will look into this.
