### ISSUE TITLE
[GLAB]: Allow Issues on GitLab

### ISSUE THREAD

**Issue by profclems** [profclems/glab#524]
Most people have criticized the fact that `glab` is a CLI tool for GitLab which is hosted on GitHub and an issue was even created by a concerned user #67.

I have been asked questions on several forums as to why `glab` is hosted on GitHub instead of GitLab. My answers have mostly been ***"For OSS visibility since most people find it convenient to contribute to FOSS on GitHub. Personally, I use GitHub to host personal projects (which `glab` is one of them) and GitLab at work."***
It's not my fault since `glab` was a small project at first just for my personal use.

To make up for that, I want to enable issues on the GitLab mirror so users can create issues directly with:
 ```sh
glab issue create -R profclems/glab
```
Since the actual activity goes on on GitHub, I'm considering creating a scheduled GitHub action that fetches all issues created on the `glab`'s [GitLab mirror](https://gitlab.com/profclems/glab) and creates them as new issues on GitHub so PRs can be created to resolve them.
If possible (well, everything is possible), new comments on GitHub recreated for the original issue on the Mirror and vice-versa.

**Comment by zemzale** [comment]
I am all for having the choice to report issues on GitLab or GitHub. 

I believe that there are plenty of people that don't wanna use GitHub, for one or another reason, but they use GitLab and would like to help with `glab` then we should provide a way for them to do that.

**Comment by profclems** [comment]
Here are a few things we need to do:

- [x] Enable Issues on the GitLab Mirror (https://gitlab.com/profclems/glab)
- [x] GitHub Action Workflow to import GitLab issues (#525) 
- [ ] sync issue events such as:
  - [ ] Labeled
  - [ ] Unlabeled
  - [ ] Commented
  - [ ] Closed
  - [ ] Reopened
- [ ] Update readme to add that users can open issues with `glab issue create -R profclems/glab`
- [x] Add to `FEEDBACK` info to `glab help` (#535)
  ```sh
  FEEDBACK
  Open an issue using 'glab issue create -R profclems/glab'
  ```
