### ISSUE TITLE
Add command to get a single pipeline

### ISSUE THREAD

**Issue by profclems** [profclems/glab#53]
**Is your feature request related to a problem? Please describe.**
Already, there are commands to list and delete pipelines. However, there is no command to view details for a single pipeline. 

**Describe the solution you'd like**
`glab pipeline get <pipeline-id>`
Additionally, the URL to the pipeline should be made available including the status and other relevant information about the pipeline

**Describe alternatives you've considered**
`glab pipeline view <pipeline-id>`

**Additional context**
None

**Comment by duritong** [comment]
What would also be nice is to watch a running pipeline.

**Comment by profclems** [comment]
> What would also be nice is to watch a running pipeline.

That is being considered in the next minor release! Thanks!
I would appreciate if you would open an issue to describe how best you want to see it so we add up.
