### ISSUE TITLE
allow listing issues and merge requests by title

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#547]
**Describe the feature or problem you'd like to solve**

I can't search issues and merge request with the `list` subcommand via the title

**Propose a Solution**

Add a `--title` switch that searches a substring inside titles using the `search` field

**Comment by profclems** [comment]
I have also been thinking about this lately.

The search parameter by default returns matches for either title or description. 

To limit the search, we'd have to use the `in` parameter to limit the scope: `?search=something&in=title`.

Maybe we can give users similar flags:
- `--search string` and 
- `--in` accepts `title | description`

and/or provide the `title` and `description` flags.


*I typed on phone*
