### ISSUE TITLE
show pipeline status of the merge request

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#557]
**Describe the feature or problem you'd like to solve**

When using `mr view` doesn't show me the status of the pipeline.

**Propose a Solution**

Show a green checkmark along with an identifier (ID) I can use to check the pipeline further via `glab pipeline view`

**Comment by profclems** [comment]
Have you tried `glab ci status`?

**Comment by zemzale** [comment]
I think it would be nice to have a small badge with the status of the pipelines in  `mr view`. Just like in the web UI when looking at MRs you can see if the pipeline failed or not. 
If I would want to find out the status of which pipeline failed and why then `ci status` should be used

**Comment by maxice8** [comment]
Never got `glab ci status` to work
