### ISSUE TITLE
Error: "Could not find remote url for gitlab"

### ISSUE THREAD

**Issue by marcolino** [profclems/glab#56]
Running any command (for example `glab issue list`) I get the error in the subject

**Description**

Running any command (for example `glab issue list`) I get the error in the subject

**Expected Behavior**

I expect a list of the issues

**Actual Behavior**

I get the error in the subject

**Possible Fix**

Documentation about requested environment variables should be more complete...

**Steps to Reproduce**

1. curl -s https://raw.githubusercontent.com/profclems/glab/trunk/scripts/quick_install.sh | sudo bash
2. export GITLAB_TOKEN=*****************
3. export GITLAB_URI=github.com
4. export GIT_REMOTE_URL_VAR=https://gitlab.com/USER/PROJECT
5. glab issue list

**Context**

Use the command `glab`

**Your Environment**

* Version used: 1.7.0
* Operating System and version: Linux ThinkCentre-E73 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by profclems** [comment]
The GIT_REMOTE_URL_VAR should contain the variable name for your git remote url. If your remote url variable is origin, run
```sh
export GIT_REMOTE_URL_VAR=origin
```
By default, it is set to `origin`. This is useful when you have two remote urls for a single repository.

**Comment by profclems** [comment]
You can also run:
```sh
glab config --global --remote-var=origin
```
If your git remote url variable that contains the gitlab repo url is `upstream`:
```sh
glab config --global --remote-var=upstream
```

**Comment by marcolino** [comment]
I have one remote url for my repository (https://gitlab.com/mypass_web/marketplace).

I do:

    export GIT_REMOTE_URL_VAR=origin
    glab config --global --remote-var=origin

and

     glab issue list

and get:

    2020/08/06 10:34:24 Could not find remote url for gitlab

**Comment by profclems** [comment]
1. Make sure you're working from the directory that contains your repo. If you haven't cloned the repo, I suggest you first clone your repo and make sure you are in the directory.

2. Run `glab config --remote-var=origin --url=https://gitlab.com` . 

3. Set your token globally with `glab config --global --token=xxxxxxxx`

Using `export` will make the variables available for only the current bash session. 
Let me know if there are still issues

**Comment by marcolino** [comment]
Ok. Sorry, I was not running from the project folder...

Now I get:

    $ env | grep GITLAB 
    GITLAB_TOKEN=*****************
    GITLAB_URI=https://github.com

    $ glab issue list                                         
    2020/08/06 11:04:51 GET https://github.com/api/v4/projects/git@gitlab.com:mypass_web/marketplace/issues: 404 {error: Not Found}

**Comment by profclems** [comment]
The GITLAB_URI should be set to https://gitlab.com and not https://github.com

Regards

**Comment by marcolino** [comment]
Thanks, sorry! (ashamed)

However I feel these variables setting documentation (included GITLAB_TOKEN) should be documented more clearly, in the installation section...

Best regards, and keep on this nice project...

**Comment by profclems** [comment]
Yeah sure... I will consider that.

I really appreciate your feedback

**Comment by marcolino** [comment]
Thanks.

And, too, consider issuing a more clear error message in case you do not find a valid current folder ... :-)

**Comment by profclems** [comment]
> Thanks.
> 
> And, too, consider issuing a more clear error message in case you do not find a valid current folder ... :-)

Noted! Thanks
