### ISSUE TITLE
Prompt to 'git init' on repo create

### ISSUE THREAD

**Issue by profclems** [profclems/glab#569]
**Describe the feature or problem you'd like to solve**

If you run `glab repo create` in a directory that isn't initialized with git the command fails:
```sh
→ glab repo create
fatal: not a git repository (or any of the parent directories): .git
git: exit status 128
```

It is required that the user first run `git init` before running `glab repo create`. 

**Propose a Solution**

If the directory isn't git initialized, the user should be prompted whether `glab` should run `git init` before creating the repo
```sh
? Directory not git initialized. Run `git init`? [Y/N]
```

**Additional context**

**Comment by cvhariharan** [comment]
Hi, if this is still up for grabs, I'd like to give this a go.

**Comment by profclems** [comment]
@cvhariharan feel free to submit a PR... Thanks!

**Comment by awa5114** [comment]
Excuse my ignorance, but why is this necessary? It seems redundant to generate a nested repo like this. Is this something that is only required by the CLI or also required by GitLab itself?

**Comment by zemzale** [comment]
You might be misunderstanding something. The command `repo create` is for creating a new repo from an existing folder. 

There is no nesting involved here.
