### ISSUE TITLE
Unable to assign milestone to a new issue with -m <Integer ID> option

### ISSUE THREAD

**Issue by teterkin** [profclems/glab#583]
**Description**

Unable to assign milestone to new issue.
According to help I could assign a milestone using -m option and integer global ID:
`-m, --milestone int        The global ID of a milestone to assign issue`
As far as I understood ID is the number assigned to milestone at the time of creation: 1, 2, 3, etc.

**Expected Behavior vs Actual Behavior**

I expect that issue will be created and Milestone with id 2 will be assigned to it.
Actually issue is created, user is assigned, but milestone is not assigned to the issue.

**Possible Fix**

**Steps to Reproduce**

1. Type this: `glab issue create -a <USER> -d "Test Issue 3" -m 2 -t "Test 3"`
2. Replace <USER> with actual user name.
2. View successful issue creation. I can see the issue at Gitlab.com
3. But it is not assigned to any Milestones.

**Logs**

`- Creating issue in ***
#3 Test 3 (less than a minute ago)
https://gitlab.com/***/***/-/issues/3`

**Your Environment**

* Version used (Run `glab --version`): glab version 1.13.1 (2020-12-28)
* Operating System and version: Ubuntu 20.10 x86_64

**Comment by profclems** [comment]
@teterkin thanks for reporting this issue!

I'm running a newer version built from `trunk`'s latest commit (b2922a7) and I can't seem to reproduce this issue.

I believe this was resolved by https://github.com/profclems/glab/pull/451 which is pending release.

**Comment by teterkin** [comment]
> I believe this was resolved by #451 which is pending release.
Ok. Then I will wait for that release.
Thank you!
