### ISSUE TITLE
Arbitrary queries over issues

### ISSUE THREAD

**Issue by asdf8601** [profclems/glab#588]
**Describe the feature or problem you'd like to solve**

I have problems to find the current issue I'm working on so I would like filtering issues according to one or more words.

**Propose a Solution**

I have thought of something like this:

```bash
glab issues list --query "my query" 
glab issues list --milestone awesome --query "my query"
```

**Comment by maxice8** [comment]
There is the `--search` that will search in the title, description or both (defined by `--in` (defaults to both)) for a substring.

**Comment by asdf8601** [comment]
Thank you for your answer, I'm using `glab version 1.13.1 (2020-12-28)` and I can't find that argument, do you mind tell me how is the usage? Here are my tries:

```
> glab issue list --search es
unknown flag: --search

Usage:  glab issue list [flags]

Flags:
  -a, --all                Get all issues
      --assignee string    Filter issue by assignee <username>
  -c, --closed             Get only closed issues
      --confidential       Filter by confidential issues
  -l, --label string       Filter issue by label <name>
      --milestone string   Filter issue by milestone <id>
      --mine               Filter only issues issues assigned to me
  -o, --opened             Get only opened issues
  -p, --page int           Page number (default 1)
  -P, --per-page int       Number of items to list per page. (default 30) (default 30)

> glab issue list --in es
unknown flag: --in

Usage:  glab issue list [flags]

Flags:
  -a, --all                Get all issues
      --assignee string    Filter issue by assignee <username>
  -c, --closed             Get only closed issues
      --confidential       Filter by confidential issues
  -l, --label string       Filter issue by label <name>
      --milestone string   Filter issue by milestone <id>
      --mine               Filter only issues issues assigned to me
  -o, --opened             Get only opened issues
  -p, --page int           Page number (default 1)
  -P, --per-page int       Number of items to list per page. (default 30) (default 30)

```

**Comment by maxice8** [comment]
Sorry, it seems like it was merged in https://github.com/profclems/glab/pull/548 but a new release hasn't be made yet.

@profclems any ETA on the next release ?

**Comment by profclems** [comment]
> @profclems any ETA on the next release ?

I should do that today. We have a lot of fixes and features pending release.

I decided we commit to a 3-week release cycle

**Comment by asdf8601** [comment]
I just upgraded glab and finally I could try these arguments which works pretty well! Nice job!
