### ISSUE TITLE
Bug: glab config crashes on run

### ISSUE THREAD

**Issue by svenk** [profclems/glab#60]
```
me@localhost % glab config    


me@localhost % glab config --help

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c16c0]

goroutine 1 [running]:
glab.Exec(0x7ffeb9c4a2ff, 0x6, 0xc000012e40, 0xc000012e70)
        glab/glab.go:101 +0x670
main.main()
        glab/cmd/glab/main.go:44 +0x36f

```

**Description**

Code actually crashes.

**Expected Behavior**

Some useful message

**Actual Behavior**

**Possible Fix**

**Steps to Reproduce**

See #59 for the setup how I built/installed glab.

**Context**

**Your Environment**

* Version used:
* Operating System and version:

**Comment by dougEfresh** [comment]
@profclems is there any reason why you didn't use a library to parse commands and args? For example, 
[cobra](https://github.com/spf13/cobra)

**Comment by profclems** [comment]
> ```
> me@localhost % glab config    
> 
> 
> me@localhost % glab config --help
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c16c0]
> 
> goroutine 1 [running]:
> glab.Exec(0x7ffeb9c4a2ff, 0x6, 0xc000012e40, 0xc000012e70)
>         glab/glab.go:101 +0x670
> main.main()
>         glab/cmd/glab/main.go:44 +0x36f
> ```
> 
> **Description**
> 
> Code actually crashes.
> 
> **Expected Behavior**
> 
> Some useful message
> 
> **Actual Behavior**
> 
> **Possible Fix**
> 
> **Steps to Reproduce**
> 
> See #59 for the setup how I built/installed glab.
> 
> **Context**
> 
> **Your Environment**
> 
> * Version used:
> * Operating System and version:


I'll look at that... At the meantime, you can set your variables with
```sh
glab config global --token=xxxxxx  --url=https://gitlab.com
```

**Comment by profclems** [comment]
> @profclems is there any reason why you didn't use a library to parse commands and args? For example,
> [cobra](https://github.com/spf13/cobra)

I wanted a lot more flexibility. I've actually looked into cobra

**Comment by dougEfresh** [comment]
From looking at your code, cobra would handle all that you need. Its really flexible.

**Comment by dougEfresh** [comment]
the CLI world, these two statements are the same: 
`glab config --token=blah --url=https://gitlab.com`
`glab config --token blah --url https://gitlab.com`
but your code doesn't support that.

**Comment by profclems** [comment]
I'll consider that! Thanks a lot

Or do you think you could open a quick PR to help with that? It'll be much appreciated

**Comment by dougEfresh** [comment]
I'll fork and open a PR
