### ISSUE TITLE
issue with long/deep paths?

### ISSUE THREAD

**Issue by ManOrs88** [profclems/glab#609]
hello,
i'm trying to use `glab ci status` to verify the pipeline status directly from the command line,
it works fine on repos with "short" paths, seem to break on "long"/"deep" ones

here are some repo url examples, i've maintained the character count in each url "section"
working:
* http://123456.123.123456.12/12345678901234/123456789012
* http://123456.123.123456.12/1234567/123456789/12345678901

not working:
* http://123456.123.123456.12/1234567/123456789/12345678901234567/12345678901234
  * returns "invalid path: /1234567/123456789/12345678901234567/12345678901234" (full url excluded the hostname)

all these are configured as ssh in git config, using http api calls

glab version 1.14.0

regards,
m

**Comment by profclems** [comment]
Hi @ManOrs88, thank for reporting this issue. 
Sorry for replying late (I saw this on a weekend).

Do you mean GitLab allows subgroups in subgroups (nested subgroups)? 

Currently `glab` supports repos in the format `HOST/OWNER/REPO` and `HOST/GROUP/NAMESPACE/REPO`

**Comment by ManOrs88** [comment]
hello @profclems ,

yes, the failing ones both have a `HOST/GROUP/NAMESPACE/DEEPNEST/REPO` form

regards,
m

**Comment by profclems** [comment]
Hmm... I wasn't really aware of that. Thanks for letting me know! I will fix that asap

**Comment by pand-app** [comment]
Hello, I confirm this issue, with a deepest repo, you are able to create unlimited deep in gitlab.

Real world example of URL not working (opensource) : https://gitlab.com/fabnum-minarm/igloo/terraform/projects/anais

Gitlab internal routing is looking for "-" segment to know that you're not looking for a deeper group.
Example : 
```
https://gitlab.com/fabnum-minarm/igloo/terraform/projects/anais/-/issues
|-------------------------------------------------------------||-||-----|
    ^ Repo part                                                 |    |
                            Ok, this sign close the repo part > |    |
         Ok, now it's the relative part of what you're looking for > |
```

**Comment by profclems** [comment]
@Nainterceptor thanks for confirming this issue.

How deep does GitLab allow nested groups? Is there a specified limit?

Initially, I thought the deepest was `GROUP/SUBGROUP/REPO`

**Comment by pand-app** [comment]
> How deep does GitLab allow nested groups? Is there a specified limit?

As far as I know, there is no limit, that's why the "-" is usefull in gitlab routing I guess.
source : https://docs.gitlab.com/ee/user/group/subgroups/#limitations

At Qonfucius we have a complex organisation with at least 5 nested groups

**Comment by profclems** [comment]
Thanks @Nainterceptor... I'm trying to work on a fix as soon as I can

**Comment by pand-app** [comment]
👍 Just made a small donation to thank your reactivity

**Comment by profclems** [comment]
This should be resolved now... Since it's an issue with high priority (affecting most users), I will do a release tonight

cc: @Nainterceptor @ManOrs88

**Comment by profclems** [comment]
I released v1.15.0 today with this issue fixed. You can update and work with it now... Cheers

**Comment by nraw** [comment]
@profclems 
I'm not sure, but would this fit as an error here? Even though I copy pasted the path with a different host from the example it still tries to check vs gitlab.com
![image](https://user-images.githubusercontent.com/15797203/108095871-a158ac80-7080-11eb-9960-e9790bb42f37.png)

**Comment by profclems** [comment]
@nraw, the `project create` command currently does not support full urls as parameter. However, you could override the gitlab host using the `GL_HOST` or `GITLAB_HOST` env variable and set the group name with `--group` flag
```sh
GITLAB_HOST=example.org glab project create myproject --group GROUP/SUBGROUP1/SUBGROUP2/SUBGROUP3/SUBGROUP4/REPO
```

**Comment by profclems** [comment]
@nraw, I think it'll be nice if `project create` supports full urls... Kindly open a separate issue for that so we work on it
