### ISSUE TITLE
Issue update command

### ISSUE THREAD

**Issue by zemzale** [profclems/glab#612]
**Describe the feature or problem you'd like to solve**
Since I haven't used the issue command a lot I didn't notice there is no `update` subcommand. 

We really do need this, since if you create an issue, we can't really update things, like labels, linked issues assigness and things like that. 

**Propose a Solution**

Let's create issue update command. It probably take the same options that `issue create` takes.

**Additional context**
Stumbled up on to this, while working on #351 and it made me think that we probably gonna need some sort of issue unlinking logic too, but that probably needs some discussion.

**Comment by maxice8** [comment]
![image](https://user-images.githubusercontent.com/30738253/107487482-f702f580-6b64-11eb-83c6-cee105e856c0.png)

**Comment by zemzale** [comment]
I did a really big overlook :smile: 
I wanted to reach out for that command, and when I typed `glab issue` and just looked at the output I saw 
```
EXAMPLES
  $ glab issue list
  $ glab issue create --label --confidential
  $ glab issue view --web
  $ glab issue note -m "closing because !123 was merged" <issue number>
  ```
  And thought that those are the only command we got.

**Comment by maxice8** [comment]
`glab issue` has a list of `CORE COMMANDS`

**Comment by zemzale** [comment]
Yeah, my brain just chose to ignore everything above the examples for some reason and I ended up thinking that we don't have these commands for some reason
