### ISSUE TITLE
Can't create MR from branch that is already pushed

### ISSUE THREAD

**Issue by zemzale** [profclems/glab#619]
**Description**
When I working I often push to remote, but don't open a MR, because I don't need that yet. When I finish up with my task, I want to create an MR, but I get an error 
```
You must be on a different branch other than "xxx"
```

**Expected Behavior vs Actual Behavior**
Expected : 
```
glab mr create
> Prompt for opening creating MR to show up
```
Actual:
```
glab mr create
You must be on a different branch other than "xxx"
```

**Possible Fix**
Something with the logic around
https://github.com/profclems/glab/blob/6e1919f24e08d870e276b255563f7d943bf65a0a/commands/mr/create/mr_create.go#L246-L254

**Steps to Reproduce**

1. Create a local branch
2. Push to remote
3. Run `glab mr create` and see error 

**Your Environment**

* Version used (Run `glab --version`): glab version 1.15.0-1-g6e1919f (2021-02-17)
* Operating System and version: Manjaro Linux

**Comment by zemzale** [comment]
I did some digging and found that the bug was introduced with the new logic of how we determine the target branch. 

When I have a branch that I have pushed to remote MergeRef comes out to be remote tracking branch.  Example: 
```
▶ glab mr create
Branch config : {RemoteName:origin RemoteURL:<nil> MergeRef:refs/heads/test-repo-push}
Source branch : test-repo-push
Target branch : test-repo-push
You must be on a different branch other than "test-repo-push"
```
Relavent part: 
https://github.com/profclems/glab/blob/trunk/commands/mr/create/mr_create.go#L679-L695

This seems to be introduced with #584

I don't fully understand the logic behind this, but shouldn't we fall back to default branch In cases when MergeRef and source branch is the same thing? 

Can someone explain or point me to a place that explains what merge ref is. because that is the part where git becomes a black box to me?

**Comment by profclems** [comment]
> ```
> You must be on a different branch other than "xxx"
> ```

Ideallly, this error should occur if you're creating a merge request 
- with the default branch of the repo (without using a fork)
- source branch is the same as the target branch (without using a fork)

So if the MR's source branch is the same as the target branch, then the merge request must be created from a fork

**Comment by zemzale** [comment]
> source branch is the same as the target branch (without using a fork)

This is happening. but that is because the logic just seems flawed.
When I create a branch of the default branch and try to create a merge request WITHOUT pushing to remote beforehand everything works just fine. 
When I create a branch of the default branch, push it to remote, and then try to create a merge request I can't do that since `MergeRef` branch is the  same as the source branch.

**Comment by profclems** [comment]
The `ReadBranchConfig` basically runs this command in a git subprocess
```
git config --get-regexp "^branch.BRANCH.(remote|merge)$"
```
where `BRANCH` is the name of the source branch. It returns 
```
branch.DEFAULT_BRANCH.remote origin
branch.DEFAULT_BRANCH.merge  refs/heads/DEFAULT_BRANCH
```
So the `MergeRef` in the `BranchConfig` struct will contain `refs/heads/DEFAULT_BRANCH`. The mergeref is the upstream's default branch

**Comment by profclems** [comment]
@zemzale I have been able to replicate this issue. Trying to get my head around on what to do to fix this asap

**Comment by profclems** [comment]
The workaround at the moment, is by explicitly setting the default branch with `--target-branch` flag
```
glab mr create --target-branch dev
```

**Comment by profclems** [comment]
> > source branch is the same as the target branch (without using a fork)
> 
> This is happening. but that is because the logic just seems flawed.
> When I create a branch of the default branch and try to create a merge request WITHOUT pushing to remote beforehand everything works just fine.
> When I create a branch of the default branch, push it to remote, and then try to create a merge request I can't do that since `MergeRef` branch is the same as the source branch.

@zemzale you were right with this. The logic is flawed. 
Currently, the remote tracking branch is used as the target branch and if unset, reverts to the default branch. We should revert to using the default branch only.

**Comment by zemzale** [comment]
Okay then. I didn't do it right away, because I didn't fully understand why and how it works.

**Comment by profclems** [comment]
@zemzale are you working on this?

**Comment by zemzale** [comment]
Yeah. PR coming right up
