### ISSUE TITLE
Wrong URL for Repositories cloned via SSH

### ISSUE THREAD

**Issue by vbrandl** [profclems/glab#63]
I have a repository that is cloned via SSH. Executing `glab issue list` in the repository gives me the following error:

```
$ glab issue list

2020/08/06 12:19:46 GET http://<gitlab-host>/api/v4/projects/ssh://git@<gitlab-host>:<ssh-port>/<owner>/<project>/issues: 404 {message: 404 Project Not Found}
```

(I replaced the actual values with placeholders)

**Comment by profclems** [comment]
While we work on fixing this, here's a quick fix:

1. Add the https remote URL to your repo to a remote origin variable
```sh
git remote add glab-origin <https-clone-url-for-your-repo>
```

2. Set the remote origin variable with:
```sh
glab config --remote-var=glab-origin
```
