### ISSUE TITLE
Error installing on MacOS Catalina 10.15.6 with Homebrew 2.4.9

### ISSUE THREAD

**Issue by grdscrc** [profclems/glab#64]
It seems there is a bug on the macos homebrew install process

**Description**
Being interested by the tool, I type `brew install -vvvv glab`, then :

**Expected Behavior**
==> glab successfully installed (or something of the sort)

**Actual Behavior**
```
==> Installing glab from profclems/tap
==> Downloading http://github.com/profclems/glab/releases/download/v1.7.0/glab_1.7.0_macOS_amd64.tar.gz
Already downloaded: /Users/igor/Library/Caches/Homebrew/downloads/20f3e1ebca103d7c16b340e05e2a366a4ae0efaf2d56cc56bdad6b1df2a9de7f--glab_1.7.0_macOS_amd64.tar.gz
==> Verifying 20f3e1ebca103d7c16b340e05e2a366a4ae0efaf2d56cc56bdad6b1df2a9de7f--glab_1.7.0_macOS_amd64.tar.gz checksum
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200806-23261-7bh4m4.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/profclems/homebrew-tap/Formula/glab.rb --verbose
tar xof /Users/igor/Library/Caches/Homebrew/downloads/20f3e1ebca103d7c16b340e05e2a366a4ae0efaf2d56cc56bdad6b1df2a9de7f--glab_1.7.0_macOS_amd64.tar.gz -C /private/tmp/d20200806-23262-4sjl7c
cp -pR /private/tmp/d20200806-23262-4sjl7c/glab_1.7.0_macOS_amd64/. /private/tmp/glab-20200806-23262-96ph2b/glab_1.7.0_macOS_amd64
chmod -Rf +w /private/tmp/d20200806-23262-4sjl7c
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - glab
```

**Possible Fix**
In the step before the error, the directory being copied is `glab_1.7.0_macOS_amd64`. Perhaps it is the correct dirname instead of just `glab` ?

**Steps to Reproduce**
1. Use MacOS Catalina 10.15.6 and Homebrew 2.4.9
2. Run `brew update`
3. Run `brew install glab` or `brew install -vvvv glab` for a more verbose output

**Context**
I'm looking forward to test how this tool could fit in my workflow ; being unable to install it does not break anything on my end, I just thought logging the issue could centralize the discussion.

**Your Environment**

* Version used: 1.7.0 (from the install logs)
* Operating System and version: MacOS Catalina 10.15.6

**Comment by profclems** [comment]
Same issue as #65

**Comment by profclems** [comment]
Whilst we work on fixing this issue, you can install with the quick install script:
```sh
curl -s https://raw.githubusercontent.com/profclems/glab/trunk/scripts/quick_install.sh | sudo bash
```
