### ISSUE TITLE
glab mr create gives error of "you must be on a different branch than <branch>"

### ISSUE THREAD

**Issue by iguyking** [profclems/glab#644]
**Description**
I get an error message when I try to create a new MR using glab.  

```
iac/terraform/infra on  lego339-minor-update-cloudwatch via 💠 default took 10m29s
❯ glab mr create
You must be on a different branch other than "master"
```

**Expected Behavior vs Actual Behavior**
MR request is started

**Steps to Reproduce**
1. create new branch in git
1. push that branch to the remote repo in gitlab
1. type in `glab mr create`

**Your Environment**

* Version used (Run `glab --version`):  glab version 1.15.0 (2021-02-15)
* Operating System and version:   Windows 10 20H2 (Build 19042.804)

**Comment by iguyking** [comment]
I am able to execute other commands against this repo using the checked out git using glab.

**Comment by zemzale** [comment]
Thanks for reporting this. This is known bug in 1.15. See issue #619.

This already has been fixed too, and should work fine in the upcoming 1.16 release.
