### ISSUE TITLE
Is git-credential working?

### ISSUE THREAD

**Issue by SolomonHD** [profclems/glab#707]
After going through the glab auth login workflow to set the personal access token, there is no credential added to .gitconfig, is there another way to configure glab to act as gh does?

**Comment by zemzale** [comment]
Hi @SolomonHD. Thanks for opening the issue, but I don't think this is a bug. `glab` stores access token at `~/.config/glab-cli/config.yml` or for local configuration it's at `REPO_ROOT/.glab-cli` which should be added to the `.gitignore` automatically. 

See https://github.com/profclems/glab#configuration

There is also a [proposal](https://github.com/profclems/glab/issues/384) for storing this in `REPO_ROOT/.git/config` so we wouldn't modify the repository. 

So if you have done the auth steps with a working access token everything should work. If there is an actual issue with running some glab command could you provide an actual example?

**Comment by SolomonHD** [comment]
Apologies my initial post wasn't specific. My issue is after I've done the glab auth login and the tokens are stored in `.config.yml`, a git clone on a repo from gitlab.com will prompt for my user/password, where I expect it to have a git credential helper, the way `gh` does. After going through the `gh` auth workflow it modifies the `~/.gitconfig` and adds: 
```
[credential "https://github.com"]
        helper =
        helper = !/usr/bin/gh auth git-credential
```

Is there some equivalent from `glab`? I tried:
```
[credential "https://gitlab.com"]
        helper =
        helper = !/usr/bin/glab auth git-credential
```
And it didn't work.

**Comment by profclems** [comment]
@SolomonHD you're right. `glab` doesn't make use of git-credential to store tokens yet. 

This is something in our `ToDo` list and I'm hoping we could release it it as part of v1.17.0 to be released this week. 
This issue is related to #661. 

Ref: https://github.com/profclems/glab/issues/661#issuecomment-802576744

**Comment by SolomonHD** [comment]
That's great news! I assume that if/when this change is implemented, the `glab auth login` workflow will modify `~/.gitconfig`?

**Comment by profclems** [comment]
Yes @SolomonHD. It will modify the `.gitconfig`

**Comment by SolomonHD** [comment]
Great, if you have a x64 .deb file with this feature I'll gladly test, if not I'll test when released!
