### ISSUE TITLE
Group clone  over https not working on a self hosted GitLab instance 

### ISSUE THREAD

**Issue by sanjeevik89** [profclems/glab#710]
**Description**
When trying to run group clone on a self hosted instance of gitlab with personal token configured, glab cli is only cloning first repo over "https".  Rest of the token's tried with "ssh" option. "ssh" option is not configured in config.yml.

This problem might occur in gitlab.com as well. I haven't tried it.

**Expected Behavior vs Actual Behavior**
glab preserves protocol as "https" for all the projects in Group while cloning. 

**Steps to Reproduce**
 Try to clone a group with nested subgroups over https in a self-hosted or public gitlab instance.

**Logs**
```
$ GITLAB_HOST="gitlab.somecompany.net" glab repo clone --group groupname/subgroup1
Cloning into 'some repo A'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 59 (delta 14), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (59/59), done.
Cloning into 'some repo B'...
The authenticity of host 'gitlab.somecompany.net (10.99.188.112)' can't be established.
ECDSA key fingerprint is SHA256:qweqweqeqweqweqweqewwqeq+ptYwLL0.
ECDSA key fingerprint is MD5:9a:7f:3f:5e:d6:21:d2:36:12:3d:ad:26:c0:3d.
Are you sure you want to continue connecting (yes/no)?
```
**Your Environment**
glab version 1.16.0 (2021-03-12)
OS - Amazon Linux

**Comment by zemzale** [comment]
Thanks for reporing this issue @sanjeevik89 

I indeed can reproduce this. Setting git protocol in config file to https only is respected for the first repository, after that it switches to SSH. 

I seem to have found the problem in our code and fix is on it's way

**Comment by sanjeevik89** [comment]
Thanks @zemzale  - Anyidea when this will be released ?
