### ISSUE TITLE
Project structure to be preserved while cloning projects in nested groups 

### ISSUE THREAD

**Issue by sanjeevik89** [profclems/glab#711]
### Description:
GitLab project structure is not preserved while clone groups.  This is a problem when projects have same name in different subgroups or nested subgroups.
 
See the below group structure. The expectation is to preserve this project tree while cloning groups.

Currently all the projects are placed in the current working directory.

```bash
group1/
├── subgroup1
│   └── project1.1
└── subgroup2
    └── project2.1
```

**Comment by zemzale** [comment]
@sanjeevik89 thanks for the issue, but this has already been done #627 

You can get this effect by using the `-p, --preserve-namespace` flag. When that is used, each namespace will be in it's own directory.

**Comment by sanjeevik89** [comment]
> @sanjeevik89 thanks for the issue, but this has already been done #627
> 
> You can get this effect by using the `-p, --preserve-namespace` flag. When that is used, each namespace will be in it's own directory.

Thanks for the quick turnaround, Much appreciated.
