### ISSUE TITLE
Support for detached pipeline in `ci trace`

### ISSUE THREAD

**Issue by tommyknows** [profclems/glab#721]
**Describe the feature or problem you'd like to solve**

When running a `glab ci trace`, I get the error message `No pipeline running or available on <branch>`. However, there is a detached pipeline on that branch, or rather on the MR of that branch.

Interestingly, `glab ci view` works fine, so I guess the logic for matching that already exists?
Or maybe I'm missing something and am using it wrong :-) 

**Propose a Solution**
Search for detached pipelines when doing `glab ci trace`

**Additional context**
https://docs.gitlab.com/ee/ci/merge_request_pipelines/

**Comment by zemzale** [comment]
Thank for the issue @tommyknows. This indeed doesn't work for detached pipelines. These commands do use a bit different way of fetching the pipelines, so that would explain that. 

If anyone wants to investigate this I am gonna mark this as help wanted.

**Comment by tommyknows** [comment]
I'm just looking at this and am wondering, should the current behaviour be kept & the the "fix" be added as a fallback, or the other way around?

Right now, `api.GetPipelines` [is being used](https://github.com/profclems/glab/blob/trunk/commands/ci/trace/trace.go#L101). If my understanding is correct, this gets all pipelines attached to a specific branch, but `detached` pipelines are...detached from that branch.

The fix is to use `api.GetCommit`, and from there access the `LastPipeline` field, like [view does it](https://github.com/profclems/glab/blob/trunk/commands/ci/view/view.go#L94).

Now, should I do `api.GetCommit`, and if `LastPipeline` isn't set try to use `api.GetPipelines`, or the other way around?

I feel like `api.GetCommit()` has a higher chance of succeeding, but I haven't really worked with Gitlab's API that much.

Let me know and I'll submit a PR with the fix!

**Comment by profclems** [comment]
@tommyknows you're right! Using the commit api has a higher chance of succeeding since the pipeline details is returned with the commit response payload.

You're free to submit a PR
