### ISSUE TITLE
dynamic completion

### ISSUE THREAD

**Issue by rsteube** [profclems/glab#724]
Added basic dynamic completion: https://github.com/rsteube/glab

[![asciicast](https://asciinema.org/a/414156.svg)](https://asciinema.org/a/414156)

related #174

**Comment by profclems** [comment]
@rsteube That is pretty cool!

Is that the changes you worked on for #722 ? If so, I would suggest you update the PR title and description, add this screenshot to the description as well, then I will review your PR.

**Comment by rsteube** [comment]
@profclems oh weird, i think that might be a bot.
