### ISSUE TITLE
glab ci status failing (glab version 1.17.0)

### ISSUE THREAD

**Issue by sanjeevik89** [profclems/glab#727]
**Description**
Getting error when running `status` subcommand on `glab ci`. Meanwhile `glab ci view` working as expected.
**Expected Behavior vs Actual Behavior**
Show status of latest pipeline with option to view logs & retry.

**Logs**
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc55aaa]

goroutine 1 [running]:
github.com/profclems/glab/commands/ci/status.NewCmdStatus.func1(0xc000666280, 0x16bdda8, 0x0, 0x0, 0x0, 0x0)
        /home/runner/work/glab/glab/commands/ci/status/status.go:88 +0x49a
github.com/spf13/cobra.(*Command).execute(0xc000666280, 0x16bdda8, 0x0, 0x0, 0xc000666280, 0x16bdda8)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004e0000, 0xc0000a8008, 0xd3, 0x2)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x349
main.main()
        /home/runner/work/glab/glab/cmd/glab/main.go:140 +0x793
```
**Your Environment**
Ubuntu 20.04 running as a Docker container on Amazon Linux

* Version used (Run `glab --version`): 1.17.0
* Operating System and version: Ubuntu 20.04

**Comment by profclems** [comment]
@sanjeevik89 thanks for opening this issue.

I can't seem to reproduce this issue. Is the pipeline a detached pipeline? If yes, then it must be related to this issue #721

**Comment by tommyknows** [comment]
I can reproduce this, will have a look together with #721.

Edit: Actually, it's not really related to #721 - the issue appears if a job requires a manual trigger and has not started yet. I'll send a separate PR for that.
