### ISSUE TITLE
Using different GitLab server Port

### ISSUE THREAD

**Issue by sh3bang** [profclems/glab#738]
Hello,

it would be nice to configure hostname and(!) port number because self hosted Gitlabs (e.g. Docker Container). 
in my case gitlab is not on 80/443.

Actually i get a error message "invalid hostname" if a answer the interactive "glab auth" dialog.

https://github.com/profclems/glab/blob/trunk/docs/source/auth/login.rst

**Comment by profclems** [comment]
@sh3bang thanks for reporting this issue... This is an issue with the hostname validation without considering ports. I will fix that asap.

In the meantime, you can set the api host via the `config set` command
```sh
glab config -g set api_host my.host.com:5000 --host my.host.com
```
Then you can set your token
```sh
glab config -g set token xxxxxx --host my.host.com
```

You can set the following configs for a host:

- **api_protocol:**  What protocol to use to access the api endpoint. Supported values: http, https
        
- **api_host:** Configure host for api endpoint, defaults to the host itself
        
- **token:** Your GitLab access token. Get an access token at https://gitlab.com/profile/personal_access_tokens
        
- **git_protocol**: What protocol to use when performing git operations. Supported values: ssh, https


~**NOTE** that if the git URL is on a non-standard port, the host should contain the port as well~
~glab config -g set api_host my.host.com:5000 --host my.host.com:5000~
See #755
