### ISSUE TITLE
glab does not work on self hosted gitlab instance with self signed certificates authority

### ISSUE THREAD

**Issue by andrzejzysko** [profclems/glab#781]
**Description**
There is an error during initial auth login configuration. It looks that glab does not work with self signed certificates.

**Expected Behavior vs Actual Behavior**

Solution to configure self signed certifacates as trusted.

**Possible Fix**

Handle system configured self signed certificates. For example for Ubuntu:
```
Copy your CA to dir /usr/local/share/ca-certificates/
Use command: sudo cp foo.crt /usr/local/share/ca-certificates/foo.crt
Update the CA store: sudo update-ca-certificates
```

**Steps to Reproduce**

1. Try to uth with gitlab instance with self signed certificate
2. glab auth login
3. Provide relevent data (see logs)
4. error using api: Get "https://corp-gitlab.com/api/v4/user": x509: certificate signed by unknown authority

**Logs**
```
glab auth login
? What GitLab instance do you want to log into? GitLab Self-hosted Instance
X Sorry, your reply was invalid: a value is required
? GitLab hostname: corp-gitlab.com
? API hostname: corp-gitlab.com
- Logging into corp-gitlab.com

Tip: you can generate a Personal Access Token here https://corp-gitlab.com/profile/personal_access_tokens
The minimum required scopes are 'api' and 'write_repository'.
? Choose default git protocol HTTPS
? Authenticate Git with your GitLab credentials? Yes
? Choose host API protocol HTTPS
- glab config set -h corp-gitlab.com git_protocol https
✓ Configured git protocol
- glab config set -h corp-gitlab.com api_protocol https
✓ Configured API protocol
error using api: Get "https://corp-gitlab.com/api/v4/user": x509: certificate signed by unknown authority
```

**Your Environment**

* glab version 1.18.1 (2021-06-10)
* Ubuntu 20.04.2 LTS
* behind corporate proxy

**Comment by profclems** [comment]
Hi @andrzejzysko, thanks for opening this issue.

glab already supports self-signed certificates. 

You can disable tls verification with:

```sh
glab config set skip_tls_verify true --host corp-gitlab.com
```

Or add the path to the self signed CA:

```sh
glab config set ca_cert /path/to/server.pem --host corp-gitlab.com
```

In theory, I believe it's possible to install the self signed root ca into your system and obviate the need for any config changes

**Comment by profclems** [comment]
After modifying the config, you can then run `glab auth login` to continue the authentication

**Comment by andrzejzysko** [comment]
I have installed already those certificates in system - no success unfortunately. This is why I created this issue.
The solution with adding certificate to config works fine so the issue can be closed now :-) Thanks.
