### ISSUE TITLE
Invalid link to Personal Access Token generation in auth login

### ISSUE THREAD

**Issue by paper42** [profclems/glab#784]
**Description**

```
$ glab auth login
? What GitLab instance do you want to log into? GitLab.com
- Logging into gitlab.com

Tip: you can generate a Personal Access Token here https://gitlab.com/profile/personal_access_tokens
The minimum required scopes are 'api' and 'write_repository'.
? Paste your authentication token: 
```
Going to https://gitlab.com/profile/personal_access_tokens results in a 404 page.

**Expected Behavior vs Actual Behavior**

**Possible Fix**

A working link is https://gitlab.com/-/profile/personal_access_tokens

**Steps to Reproduce**

1. auth login
2. select gitlab.com
3. try visiting the link in a browser

**Logs**

**Your Environment**

* Version used (Run `glab --version`): glab version 1.18.1
* Operating System and version: Void Linux

**Comment by profclems** [comment]
Hi @paper42, thanks a lot for opening this issue. 

I'm not sure when this change occurred but GitLab used to automatically redirect https://gitlab.com/profile/personal_access_tokens to https://gitlab.com/-/profile/personal_access_tokens.

I just tested on self hosted instances like gitlab.gnome.org and salsa.debian.org and it still works so I guess the error occurs only GitLab.com
- https://gitlab.gnome.org/profile/personal_access_tokens --> https://gitlab.gnome.org/-/profile/personal_access_tokens
- https://salsa.debian.org/profile/personal_access_tokens --> https://salsa.debian.org/-/profile/personal_access_tokens 

I will submit a fix asap but it is open in case you or anyone want to submit a quick PR with a fix.
