### ISSUE TITLE
glab mr diff

### ISSUE THREAD

**Issue by profclems** [profclems/glab#79]
Show changes with annotations

Reference:
https://docs.gitlab.com/ee/api/merge_requests.html#get-mr-diff-versions

**Comment by unjuli** [comment]
I'd like to pick this up too if still available.

**Comment by profclems** [comment]
That's great @anjali-sharma

**Comment by unjuli** [comment]
@profclems What do you mean by annotations here?

**Comment by profclems** [comment]
Comments or notes added to the changes
You can leave that out for now and show only the diff
