### ISSUE TITLE
Configuration could be in .git/config

### ISSUE THREAD

**Issue by rossburton** [profclems/glab#791]
I added some local configuration and glab writes a new file `.glab-cli/config.yml` and adds that to `.gitignore`.

As by definition we're already in a Git repository, and Git has support for arbitrary key-value pairs at both the repository and global scope, why can't glab store configuration there?

**Comment by profclems** [comment]
Related to #384 

Thanks for bringing it up again... I have pushed it high up on my todo list. It is, however open for whoever would like to take it up
