### ISSUE TITLE
Gui based merge request review

### ISSUE THREAD

**Issue by profclems** [profclems/glab#80]
`glab mr review <id>` to review a merge request directly on the cli.

Can be implemented with [gocui](https://github.com/jroimartin/gocui)

**Comment by pgollangi** [comment]
Interesting!! I'll have a thought on this. 
@profclems  any thoughts on UI interaction?

**Comment by profclems** [comment]
I implemented the GUI for viewing pipeline(#95) with [tview](https://github.com/rivo/tview). [Gocui](https://github.com/jroimartin/gocui) seems to be no longer maintained
