### ISSUE TITLE
Set "Delete source branch" on MR creation

### ISSUE THREAD

**Issue by gabm** [profclems/glab#806]
We want to set the "delete source branch" checkbox per default but glab doesn't allow me to do that. Is there a possibiliy, e.g. via config?

**Comment by profclems** [comment]
@gabm thanks for opening this issue. This is currently not possible to set via config, but you can create an alias for that using the `glab alias` command.

You can set the alias with:
```sh
glab alias set mrd "mr --remove-source-branch"
```
and you can use it like:
```sh
glab mrd

#this is translated to 
#=> glab mr create --remove-source-branch
```

**Comment by gabm** [comment]
thats lovely! .. I didn't know about aliases but I am already convinced that they are very powerful... thank you for that!
