### ISSUE TITLE
404 failed to parse unkown error format

### ISSUE THREAD

**Issue by trytuna** [profclems/glab#81]
**Description**
If I run the issue list command I gonna get the following error message:

```
% glab issue list
2020/08/10 10:39:32 GET https://gitlab.x.y.z.de/users/sign_in: 404 failed to parse unknown error format
```

I can get a list of issues if I curl the GitLab API like so `curl --header "PRIVATE-TOKEN: <token>" https://gitlab.x.y.z.de/api/v4/issues`.

```
% cat ~/.glab-cli/config/.env 
GITLAB_URI=https://gitlab.x.y.z.de
GITLAB_TOKEN=<token>
GIT_REMOTE_URL_VAR=origin
```

**Expected Behavior**
List the a list of open issues

**Your Environment**
I am running the latest macOS (10.15.6) and glab (1.8.0) version.

GitLab Version: 13.2.1

**Comment by trytuna** [comment]
I solved it by myself. It actually was a misconfiguration in the apache reverse proxy.

If someone is facing the same error message this might help: https://forum.gitlab.com/t/webide-wont-open/18680/19

**Comment by profclems** [comment]
@trytuna, glad you found a solution and shared. Thanks!
