### ISSUE TITLE
ssh-key: manage different hosts

### ISSUE THREAD

**Issue by rsteube** [profclems/glab#815]
**Description**
ssh keys cannot  be managed for different hosts

**Expected Behavior vs Actual Behavior**
can currently only manage for on host (`gitlab.com` in my case)

**Possible Fix**
add `--repo` flag to `ssh-key` command

**Comment by rsteube** [comment]
or rather `--hostname` as in the `api` command

**Comment by profclems** [comment]
@rsteube thanks for reporting this issue. You're right, this was an oversight. 

Are you available to open a quick PR for it? It is also open if anyone would like to open a PR for this fix.

We only need to add:

```
cmdutils.EnableRepoOverride(cmd, f)
```

to https://github.com/profclems/glab/blob/trunk/commands/ssh-key/ssh-key.go.

This is the diff:

```diff
func NewCmdSSHKey(f *cmdutils.Factory) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "ssh-key <command>",
		Short: "Manage SSH keys",
		Long:  "Manage SSH keys registered with your GitLab account",
	}

+	cmdutils.EnableRepoOverride(cmd, f)

	cmd.AddCommand(cmdAdd.NewCmdAdd(f, nil))
	cmd.AddCommand(cmdGet.NewCmdGet(f, nil))
	cmd.AddCommand(cmdList.NewCmdList(f, nil))

	return cmd
}
```

**Comment by rsteube** [comment]
Isn't the shh-key configured rather per host than per repository?

**Comment by profclems** [comment]
> Isn't the shh-key configured rather per host than per repository?

Yeah you're right. I didn't get enough time to think through this. 

Also, the `--repo` flag accepts full git ssh and http(s) URLs which will be parsed and the httpClient will be the instantiated for the hostname in the URL. So I'm not sure whether to just consider the `--repo` flag or introduce `--host | -h` flag to get just the hostname.

**Comment by profclems** [comment]
GitLab does have project specific ssh-key which is called the "deploy keys" but has an API different from the SSH Keys API.
So maybe, to make sure the command is specific, we'll just introduce the `--host | -h` flag for the `ssh-key` command to get the hostname.

Then we introduce a new `glab deploy-key` command that makes use of `--repo` flag.
