### ISSUE TITLE
glab: command not found on Docker image

### ISSUE THREAD

**Issue by bjschafer** [profclems/glab#816]
**Description**

When launching the latest Docker image with e.g. `docker run -it --rm profclems/glab:latest`, it returns `/entrypoint.sh: line 24: glab: command not found`

**Expected Behavior vs Actual Behavior**
I'd expect it to launch the `glab` executable.

**Possible Fix**
Seems like `glab` isn't in the default `$PATH`, because it's located at `/usr/glab`. Either move `glab` into `/usr/local/bin` (arguably more correct), or add `/usr` to `$PATH`.

**Steps to Reproduce**
1. `docker run -it profclem/glab:latest`
2. See `glab: command not found`
3. Cry a little inside.

**Your Environment**
* Version used (Run `glab --version`): 1.19.0

**Comment by profclems** [comment]
@bjschafer thanks for opening this issue. 

I guess I would have to do a new release asap.

Seems the docker image works for previous versions up to v1.18.1, I don't know why this is happening.

> Seems like glab isn't in the default $PATH, because it's located at /usr/glab. Either move glab into /usr/local/bin (arguably more correct), or add /usr to $PATH.

We run `apk add --allow-untrusted /tmp/glab_*.apk` in the dockerfile so I expect `apk` to find the right path for glab.

**Comment by profclems** [comment]
I just found out that the new `goreleaser` update doesn't package nfpms in a /bin directory.

I have opened a PR with a fix. I will do a new release with this.

Thanks a lot @bjschafer

**Comment by profclems** [comment]
Just released [v1.20.0](https://github.com/profclems/glab/releases/v1.20.0)
