### ISSUE TITLE
404 error when creating release

### ISSUE THREAD

**Issue by TheSimpleZ** [profclems/glab#835]
**Description**

Running `glab release create test` in a fresh repo gives the below error:
```bash
➜  test-repo git:(master) glab release create test
• Validating tag test
• Tag does not exist.
• No ref was provided. Tag will be created from the latest state of the default branch
• using default branch "main" as ref

? Release Title (optional) 
? Release notes Leave blank
• creating or updating release repo=SimplyZ/test-repo tag=test
x release failed after 0.21s error=GET https://gitlab.com/api/v4/projects/SimplyZ/test-repo/releases/test: 404 {message: 404 Not Found}
```

The repo is public, and `glab auth status` shows all green checkmarks.

I would expect the above to work.

**Steps to Reproduce**
1.  Create a fresh repo
2. Make a commit
3. Try to create a release

**Your Environment**

* Version used (Run `glab --version`):
glab version 1.20.0 (2021-08-11)

* Operating System and version:
Manjaro 21.1

**Comment by profclems** [comment]
@TheSimpleZ thanks for reporting this issue.

The GitLab GET Release endpoint returns 403 when the release does not exist. I think that has been fixed in the recent GitLab releases. 

I will submit a fix asap.
