### ISSUE TITLE
Refactor to enable packaging glab inside another golang CLI tool (overriding config location)

### ISSUE THREAD

**Issue by addshore** [profclems/glab#843]
**Describe the feature or problem you'd like to solve**

I would like to incorporate a `gitlab` sub command into a CLI I am developing for MediaWiki / Wikimedia developers.
This would work as part of an already released binary, and be automatically configured to point to the Wikimedia Gitlab instance

**Propose a Solution**

Refactor `glinstance` and or Factory to allow overriding the location of the configuration file as well as the domain to be use for gitlab.
This would allow users to use a version of the glab CLI packaged within the mwcli as well as a standalone glab binary pointing to the default instance.

**Additional context**

It would appear something like this:

![image](https://user-images.githubusercontent.com/3308769/134231370-1735a171-a4f6-40ca-97ca-c2f4bdc7647b.png)

Other CLI codebase: https://gitlab.wikimedia.org/releng/cli

**Comment by profclems** [comment]
Hi @addshore, I didn't really expect a use case like this for `glab`. With this, you need access to the internal packages like `glinstance` and `config`.

For instance, to override the default host, you need to use the `glinstance.OverrideDefaultProtocol(host)` which is in the [internal/glinstance](https://github.com/profclems/glab/blob/c608850edb768d2a9be2d98874440a3643a32a42/internal/glinstance) package.

https://github.com/profclems/glab/blob/c608850edb768d2a9be2d98874440a3643a32a42/internal/glinstance/host.go#L46-L48

I can confirm that it's safe to move these packages to the `pkg` folder but I don't know if I will be able to work on this anytime soon. This is open in case you'd like to take this up.

**Comment by addshore** [comment]
Great!
I'll try and have a go moving these things around!

**Comment by addshore** [comment]
Ahh right there is per host config already it seems?

```
./bin/mw glab config get -g
Error: accepts 1 arg(s), received 0
Usage:  mw glab config get <key> [flags]

Flags:
  -g, --global        Read from global config file (~/.config/glab-cli/config.yml). [Default: looks through Environment variables → Local → Global]
  -h, --host string   Get per-host setting

accepts 1 arg(s), received 0
```

So I could leave the configuration location etc totally untouched? just changing the default host probably?

**Comment by profclems** [comment]
Yeah you only need to change the default host and leave the config untouched. 
`glab` already supports per-host config
