### ISSUE TITLE
Debian package 1.21.0 installs binary to /usr/bin/bin/glab

### ISSUE THREAD

**Issue by jakub-valenta** [profclems/glab#846]
I have downloaded and installed glab from deb package glab_1.21.0_Linux_x86_64.deb on debian bullseye and it installed executable to /usr/bin/bin/glab instead of to /usr/bin/glab. This prevents using the program because on most systems /usr/bin/bin is not in the path.

Please change path to /usr/bin/glab.

**Comment by profclems** [comment]
Thanks for reporting this issue @jakub-valenta. This has been fixed now. I just release v1.21.1
