### ISSUE TITLE
`pipeline view` showing incorrect triggered timestamp

### ISSUE THREAD

**Issue by junderhill** [profclems/glab#858]
**Description**

When using `glab pipeline ci view` the timestamp within the header is using the commit timestamp and not the pipeline triggered time.

**Expected Behavior vs Actual Behavior**

Shows the commit time not the pipeline triggered time.

**Possible Fix**

The linked code below is using the commit timestamp.
[https://github.com/profclems/glab/blob/3d9f97c28ee86721b2f1e6ae009b791945e42261/commands/ci/view/view.go#L110](https://github.com/profclems/glab/blob/3d9f97c28ee86721b2f1e6ae009b791945e42261/commands/ci/view/view.go#L110)

**Steps to Reproduce**

1. Type this '...'
2. View the output '....'
3. See error

**Logs**

**Your Environment**

* Version used (Run `glab --version`): glab version 1.21.1 (2021-09-28)
* Operating System and version: macOS Monterrey Beta 8

**Comment by junderhill** [comment]
Will be creating pull request for this fix shortly.

**Comment by profclems** [comment]
Hi @junderhill, thanks for opening this issue!

Yeah you're right, instead of using the `opts.Commit.AuthoredDate`, we should use `opts.Commit.LastPipeline.CreatedAt`
