### ISSUE TITLE
mr note: variable being interpreted in note text

### ISSUE THREAD

**Issue by Spreadcat** [profclems/glab#873]
**Description**

When trying to add a note to an existing MR, using Markdown syntax to mark code text resulted in the marked text

- being ommited from the note
- being interpreted otherwise.

**Expected Behavior vs Actual Behavior**
Actual behavior:

```bash
$ glab mr note 42 -m "Waiting for clarification on variable `foo` before it can be merged.`
foo: command not found
https://gitlab.example.com/.../.../merge_requests/42/note#8888
```

The note in the GUI contained

> Waiting for clarification on variable before it can be merged.

---

Expected behavior:
```bash
$ glab mr note 42 -m "Waiting for clarification on variable `foo` before it can be merged.`
https://gitlab.example.com/.../.../merge_requests/42/note#8888
```

The note in the GUI contains

> Waiting for clarification on variable `foo` before it can be merged.

**Possible Fix**

My (wild) guess it that the input string is interpreted at some level.

**Steps to Reproduce**

1. Create an issue
2. Create an MR
3. Add a note to the MR using glab.
4. See problem and verify with GIO.

**Your Environment**

* Version used (Run `glab --version`): 1.21.1
* Operating System and version: Ubuntu 20

**Comment by profclems** [comment]
This is an expected behaviour in bash. It happens with `git` as well. In bash, strings wrapped with backticks are interpreted as commands.

You have to escape it with `\`:

```
$ glab mr note 42 -m "Waiting for clarification on variable \`foo\` before it can be merged."
```

**Comment by Spreadcat** [comment]
Yes, I see. I forgot about bash variable interpolation for a second and were not paying attention to that I used double quotes here.

Both these solutions work as expected:

```bash
$ glab mr note 42 -m "Waiting for clarification on variable \`foo\` before it can be merged."
$ glab mr note 42 -m 'Waiting for clarification on variable `foo` before it can be merged.'
```

Closing, since this isn't a bug - just me being stupid
