### ISSUE TITLE
issue create: weight parameter not correct in GUI

### ISSUE THREAD

**Issue by Spreadcat** [profclems/glab#874]
**Description**

When creating a new issue and supplying the weight parameter `-w`, the value is not being taken correctly into the GUI for further adjustment. This leads at the end to the parameter not being set at all.

**Expected Behavior vs Actual Behavior**

Actual Behavior:

```bash
glab issue create -t 'Test issue' -w 2
```
ends up with a priority of 0/empty when using "Continue in browser" during issue creation.

Expected Behavior:

```bash
glab issue create -t 'Test issue' -w 2
```

Ends up with a priority of 2 when using "Continue in browser" during issue creation.

- The problem does not surface when the step "Continue in browser" is being omitted.

**Steps to Reproduce**

1. Start a new issue
   ```bash
   glab issue create -t 'Testissue' -w 2
   ```
1. Fill out the issue stuff and choose "Continue in browser"
1. When the Browser window opens the weight has been added as `/weight %2`.
1. Create the issue and verify no weight has been assigned to the issue.

FYI: removing `%` from the text field manually during issue creation fixes the issue.

**Your Environment**

* Version used (Run `glab --version`): 1.21.1
* Operating System and version: Ubuntu 20

**Comment by profclems** [comment]
@Spreadcat thanks for reporting this issue.

So the possible fix now is to remove the extra `%s` from this line https://github.com/profclems/glab/blob/f127d7e62540684d0ba422247fe4d1a03ecfc803/commands/issue/create/issue_create.go#L405
