### ISSUE TITLE
feat: List all merge requests assigned for review for a Gitlab group (and all subgroups)

### ISSUE THREAD

**Issue by kayman-mk** [profclems/glab#909]
**Describe the feature or problem you'd like to solve**
I didn't find the option to list all merge requests assigned to me for review. `glab mr list --reviewer=@me` works on current repository only. I have 70 projects organized by groups so it would be nice to run a `glab mr list --reviewer=@me -R my-group` to show all merge requests I have to review.

**Propose a Solution**
I am not an expert, but could we use the `-R`flag? At the moment I have to enter owner/repo or group/namespace/repo which does not help here. So what about `glab mr list --reviewer=@me -R my-group-name`

**Additional context**
None

**Comment by kayman-mk** [comment]
I found the following workaround:
```
# show merge requests to be reviewed
alias srev='\glab api "groups/GITLAB_TOP_GROUP/merge_requests?state=opened&reviewer_username=MY_GITLAB_USERNAME&order_by=created_at&sort=desc" | jq -r "(.[] | [(.author.name | \" \"* (26-length) + .), .title]) | @tsv"'
# go to merge request $1 from the list above
alias grev='show_mr(){ echo `\glab api "groups/GITLAB_TOP_GROUP/merge_requests?state=opened&reviewer_username=MY_GITLAB_USERNAME&order_by=created_at&sort=desc" | jq -r ".[$1].web_url"`; unset -f show_mr; }; chrome `show_mr`'
```
Replace `GITLAB_TOP_GROUP` and ' MY_GITLAB_USERNAME` with appropriate values.

**Comment by kayman-mk** [comment]
@profclems any idea how this could be solved?

**Comment by zemzale** [comment]
We can just add a flag `-g/--group` that we can use to list MRs for a group. 

It would simply use the same API you have in your alias, instead of the project API. Will try to write up a PR right now.

**Comment by kayman-mk** [comment]
@zemzale Nice!
