### ISSUE TITLE
Could not find remote url for gitlab. Run git config

### ISSUE THREAD

**Issue by enchilada-composer** [profclems/glab#91]
Hello guys,

total noob here. As the title suggests, I'm not able to see current merge requests in GitLab via
`glab mr list`

`git remote -v` gives me 

```
origin	ssh://git@############:2222/projectName/exampleName.git (fetch)
origin	ssh://git@############:2222/projectName/exampleName.git (push)
```

what am I doing wrong? I googled a lot to the point where I was not able to pull anything from master anymore. I really wanna use this great tool without breaking my project.

Can someone help?

**Comment by ombre8** [comment]
have the same issue, I think this is a Bug, i configured glab the same way i did on another computer (with older version on which it worked)

**Comment by brackindustries** [comment]
Try running the configuration command `glab config --token=<YOUR-GITLAB-ACCESS-TOKEN> --url=https://gitlab.com` and ensure the file `~/.glab-cli/config/.env` is present after that. 

It should contain stuff like 
```
GITLAB_TOKEN=xxx
GITLAB_URI=https://gitlabinstance.test
```

This solved it for me.

**Comment by profclems** [comment]
Take a look at this https://github.com/profclems/glab/issues/63#issuecomment-670022252

**Comment by enchilada-composer** [comment]
Thanks for the replies!

I tried the above and did what was described in #63. Now I get:
`2020/08/12 07:36:36 GET https://gitlab.com/api/v4/projects/groupName/projectName/issues: 401 {message: 401 Unauthorized}`

I think I only used gitlab via ssh before. When I try to 
`git remote add glab-origin <https-clone-url-for-your-repo>`
and
`glab config --remote-var=glab-origin`
then
`git remote -v` gives me:
`glab-origin	https://gitlab.#######/####/###.git (fetch)
glab-origin	https://gitlab.#######/####/###.git (push)
origin	ssh://git@gitlab.#######:2222/####/###.git (fetch)
origin	ssh://git@gitlab.#######:2222/####/###.git (push)`

When I try to 
`git remote add glab-origin <ssh-clone-url-for-your-repo>`
it says
`fatal: remote glab-origin already exists.`

**Comment by enchilada-composer** [comment]
Fixed!
I messed up the url part in 
`glab config --token=<YOUR-GITLAB-ACCESS-TOKEN> --url=https://gitlab.com`

It is working now, thank you!

**Comment by profclems** [comment]
> Fixed!
> I messed up the url party in
> `glab config --token=<YOUR-GITLAB-ACCESS-TOKEN> --url=https://gitlab.com`
> 
> It is working now, thank you!

Great!
Also note that setting configuration without the `--global` flag sets it for the current repo directory. To set global configurations that persist across all repos add the global flag
`glab config --token=<YOUR-GITLAB-ACCESS-TOKEN> --url=https://gitlab.com`
