### ISSUE TITLE
Does this work with gitlab.com "groups"?

### ISSUE THREAD

**Issue by ahillio** [profclems/glab#922]
I have a gitlab group https://gitlab.com/lrn.software that I created from my personal account.  A few of the repositories in that group have issues in their issue queues.  But when I do `glab issue list` it reports:

`none of the git remotes configured for this repository points to a known GitLab host. Please use `glab auth login` to authenticate and configure a new host for glab`.

But I've already done that.  I authenticated with `glab auth login --stdin < alecs-access-token.txt` as the docs instruct.

Is there some other configuration required to reach the repositories of my account's groups?

**Comment by zemzale** [comment]
Hey @ahillio. Are you running the command inside one of the repositories of this group? Generally `glab` works with individual repositories, with some support from groups (milestones, labels, boards), but there is currently no support for listing all the issues inside a group. 

That means that you can run `glab issue list` from a repository and it would list that repositories issues, but you can't list the issue from the whole group. 

There might be a case made for maybe adding some `--group` flag that would list all the issues from the group.

**Comment by ahillio** [comment]
oh Thank you @zemzale!!! 

Is that documented?  It might be a reasonable assumption to make that `glab` needs to be run from inside a repo but I didn't assume that myself.  I don't see anything in the README about it.

I can indeed see issues for my repos within this group.  And if there's a way to have the list print to the terminal than a simple shell script can loop through the groups repositories and run `glab issue list` in each one.... but I haven't yet seen if that's a configurable option (??) (though this becomes a different topic).

Thanks again.

**Comment by ahillio** [comment]
This error message:

`none of the git remotes configured for this repository points to a known GitLab host. Please use glab auth login to authenticate and configure a new host for glab.`

was a little misleading.  It made me think that the problem was in regards to authentication and access control.  But the actual problem was that I wasn't in the directory of a repository.

**Comment by ahillio** [comment]
Well, the first part of that message could have helped me, but the latter part confused me.

**Comment by ahillio** [comment]
Getting lists of issues for all repos in group:

```sh
cd path/to/group-directory
for r in $(find -maxdepth 1 -type d | sed 's|\./||g' | sed '/^\./d'); do
  cd $r
  glab issue list | cat
  cd ..
done
```
