### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by profclems** [profclems/glab#94]
If this cool tool doesn't even have a shiny logo, how are we supposed to pitch a tool to end-users?

Somebody else is going to have to take this one on because my design sucks 😃. Well, yeah, I'm a CLI guy!
Does anybody want to give back to us for this OSS by contributing some cool branding for this project?

**Comment by majoal0** [comment]
I made this one:

![glab-logo-design-100](https://user-images.githubusercontent.com/9063085/90530075-d7a58580-e14a-11ea-9727-4f592f7dcf2e.png)

**Comment by profclems** [comment]
Impressive!
Could you add it to the top of the readme and open a PR so GitHub recognizes you as a contributor?
Thank you
