### ISSUE TITLE
fatal: Unable to find remote helper for 'https' exit status 128

### ISSUE THREAD

**Issue by sebademasi10** [profclems/glab#943]
Hi everyone!

I am trying to create a MR with the following command:

`glab mr create -s testing -b develop -y -f --fill-commit-body`

Both of them exist:

`git branch --all`

>  dev-cba
\* develop
  testing
  remotes/origin/dev-cba
  remotes/origin/develop
  remotes/origin/feature/nuevo-contrato
  remotes/origin/feature/nuevo-contrato-adjudicatario
  remotes/origin/fix
  remotes/origin/rm-orm
  remotes/origin/testing
  remotes/tfs-gov/dev-cba

But I am getting the following output: 
> fatal: Unable to find remote helper for 'https'
exit status 128

I have tried by installing `libcurl4-openssl-dev` as suggested [here](https://stackoverflow.com/questions/8329485/unable-to-find-remote-helper-for-https-during-git-clone) and reinstalling git using apt:

`sudo apt install libcurl4-openssl-dev`
`sudo apt remove git`
`sudo apt install git`

But I get the same output
> fatal: Unable to find remote helper for 'https'
exit status 128

Please feel free to ask any additional information if necessary and thanks in advance! :relieved:

**Comment by zemzale** [comment]
Hey. This looks like a git issue, but we can try to figure out what is the problem. 

Few questions: 
- Are you using HTTPS in protocol for the repo or SSH? You can check this with `git remote -v` and see if the remotes start with HTTPS or something like git@
- What kind a protocol have u set for `glab`? You can see this with `glab config get GIT_PROTOCOL` or by checking your `.config/glab-cli/config.yaml` file
- Can you do a clean clone of the repo using HTTP or does only this command fail?

**Comment by zemzale** [comment]
Also how did you install `glab`? Did you use snap? There have been some problems with that.

**Comment by sebademasi10** [comment]
Hi @zemzale! Thanks for answer :relieved: 

> Are you using HTTPS in protocol for the repo or SSH? You can check this with git remote -v and see if the remotes start with HTTPS or something like git@ 

I am using HTTPS

> What kind a protocol have u set for glab? You can see this with glab config get GIT_PROTOCOL or by checking your .config/glab-cli/config.yaml file

I have set `HTTPS` when I ran `glab` first time

> Can you do a clean clone of the repo using HTTP or does only this command fail?

Yes, I use the repo every day to work

> Also how did you install glab? Did you use snap? There have been some problems with that.

I installed `glab` from snap, as described [here](https://github.com/profclems/glab#snapcraft)

**Comment by zemzale** [comment]
I have a suspicion that snap is at fault. I saw a similar issue for `gh`. You could try to download the precompiled binary and try to use that and see if that fixes the problem.

**Comment by sebademasi10** [comment]
Hi again! I have done what you suggested and it works, thanks very much!

**Comment by adri326** [comment]
I have also installed `glab` using the snap store, and am also running into this issue. Installing the `.deb` fixed it, so it should maybe be mentioned in the README that the snap can cause issues?
