### ISSUE TITLE
Conveniently edit tite/description of issues and merge requests in editor

### ISSUE THREAD

**Issue by mxhe1** [profclems/glab#945]
**Describe the feature or problem you'd like to solve**
Sometimes I come to a situation where I want to make changes to a merge request description, so having a single command for editing fields in issues and merge requests would be very convenient.  

**Propose a Solution**
Proposed syntax for editing the description of merge request 123

`glab mr 123 update -d` (no arguments)

OR

`glab mr 123 edit -d`

opens the description in my editor and updates the merge request when closing the editor.

**Comment by zemzale** [comment]
Hey @mxhe1. We have an issue for this already open at #466. 

I will close this as a duplicate, but gonna bump the priority for the original issue. I don't know if I am gonna have time to work on this feature, but if you want you can have a crack on the problem yourself.

**Comment by mxhe1** [comment]
Thanks for the quick response. I'm not very familiar with go but I'll give it a try if I have time.
