### ISSUE TITLE
Can not authenticate with self hosted instance and api endpoint http://localhost:8888/gitlab/api/v4/user

### ISSUE THREAD

**Issue by a333klm** [profclems/glab#960]
**Description**
`glab auth login` seems not to work when the api endpoint is not under `http://localhost:8888` but `http://localhost:8888/gitlab`

![image](https://user-images.githubusercontent.com/29760462/154800996-2878da83-d453-4306-9908-a7a81ee57349.png)

**Your Environment**

* Version used (Run `glab --version`): glab version 1.22.0-19-gff1032b (2022-02-16)

* Operating System and version: Ubuntu 18.04.6 LTS

**Comment by zemzale** [comment]
hey @a333klm If the APi endpoint is under `http://localhost:8888/gitlab` then when running running auth you should put that under API hostname

**Comment by a333klm** [comment]
hey @zemzale 
I think I found the issue in the code. The hostname validator accepts only digits after `:`
So to change this behavior, the regex needs to be adapted.
[See this Code line](https://github.com/profclems/glab/blob/83eac0195c87365c98856e0e034fe2985354d93f/commands/auth/login/login.go#L324)

(regex for reference)
`^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])(:[0-9]+)?$`

I think at the moment the regex allows a portnumber. But something like localhost:8888/gitlab does not work.
