### ISSUE TITLE
no way to choose a different name than the directory?

### ISSUE THREAD

**Issue by eiro** [profclems/glab#962]
hello,

```
$ pwd
/tmp/testalacon
$ glab repo create -n testalacon3
Created repository  myself/ testalacon3 on GitLab: https://mind.your.biz/myself/testalacon
```
I expected  https://mind.your.biz/myself/testalacon3. is there a way to get this right ?

**Comment by zemzale** [comment]
Hey @eiro. You can simply provide a path to the repo as an argument. To get what you desire would be 
```sh
glab repo create testalacon3
```

The `-n/--name` flag is for setting the visible name for the repo, which can be changed after creation e.g.
![image](https://user-images.githubusercontent.com/14844365/155669247-cb891cea-588a-4491-af34-b5b65468cb0e.png)
