### ISSUE TITLE
Group clone function should probably nest groups

### ISSUE THREAD

**Issue by alerque** [profclems/glab#965]
The `glab repo clone -g <group> -G` option allows cloning all repositories in a group recursively, but it ends up cloning a flat structure unlike the nested group structure of the source groups. I would expect it to nest the directories by default just as in the groups.

**Comment by zemzale** [comment]
Hey @alerque if I underststand correctly you are looking for  flag for 
```
-p, --preserve-namespace    Clone the repo in a subdirectory based on namespace
``` 

So instead of cloning them as 
```
\repo1
\repo2
\repo3
```
They would be cloned as
```
\group1\repo1
\group2\repo2
\group2\subgroup\repo3
```

**Comment by alerque** [comment]
Yes, sorry I missed that in the docs!
