### ISSUE TITLE
Could not find remote url for gitlab. Run git config

### ISSUE THREAD

**Issue by baurmatt** [profclems/glab#97]
**Description**
glab always complains about `Could not find remote url for gitlab. Run git config`.

```
$ glab --version
glab version 1.8.1 ()
git version 2.28.0
Made with ❤ by Clement Sam <clementsam75@gmail.com> and contributors
$ glab config --token=$GITLAB_CODE_API_PRIVATE_TOKEN --url=https://gitlab.example.org
Environment variable(s) updated
$ git remote -v
origin	git@gitlab.example.org:group/subgroup1/subgroup2/ingress-nginx.git (fetch)
origin	git@gitlab.example.org:group/subgroup1/subgroup2/ingress-nginx.git (push)
$ glab mr list
2020/08/12 15:13:43 Could not find remote url for gitlab. Run git config
```

**Expected Behavior**
It works

**Actual Behavior**
`Could not find remote url for gitlab. Run git config`

**Possible Fix**

**Steps to Reproduce**
```
$ glab --version
glab version 1.8.1 ()
git version 2.28.0
Made with ❤ by Clement Sam <clementsam75@gmail.com> and contributors
$ glab config --token=$GITLAB_CODE_API_PRIVATE_TOKEN --url=https://gitlab.example.org
Environment variable(s) updated
$ git remote -v
origin	git@gitlab.example.org:group/subgroup1/subgroup2/ingress-nginx.git (fetch)
origin	git@gitlab.example.org:group/subgroup1/subgroup2/ingress-nginx.git (push)
$ glab mr list
2020/08/12 15:13:43 Could not find remote url for gitlab. Run git config
```

**Context**

**Your Environment**

* Version used:
* Operating System and version:

**Comment by profclems** [comment]
Run:
`glab config` or `glab config --global` and follow the prompt

Note that without the `--global` flag, glab sets the configuration only for the current repo directory

**Comment by baurmatt** [comment]
Same error :(

```
$ glab config
? Enter default Gitlab Host (Current Value: ):  https://gitlab.example.org
? Enter default Gitlab Token:  $GITLAB_CODE_API_PRIVATE_TOKEN
? Enter Git remote url variable (Current Value: ):  git@gitlab.example.org:group/subgroup1/subgroup2/ingress-nginx.git
Environment variable(s) updated
$ glab mr list
2020/08/12 16:00:00 Could not find remote url for gitlab. Run git config
```

**Comment by profclems** [comment]
> Same error :(
> 
> ```
> $ glab config
> ? Enter default Gitlab Host (Current Value: ):  https://gitlab.example.org
> ? Enter default Gitlab Token:  $GITLAB_CODE_API_PRIVATE_TOKEN
> ? Enter Git remote url variable (Current Value: ):  git@gitlab.example.org:group/subgroup1/subgroup2/ingress-nginx.git
> Environment variable(s) updated
> $ glab mr list
> 2020/08/12 16:00:00 Could not find remote url for gitlab. Run git config
> ```

The remote url variable is the git remote variable that contains the git url. Example is `origin` or `upstream` or any other defined varibale. You are providing the git URL instead of the variable.
Run:
`glab config --global --remote-var=origin`

`glab` uses the variable provided to get the URL from git configuration.

**Comment by baurmatt** [comment]
Ah, now I get is. Can you just default the Git remote url variable to `origin`. That should be fine for 98% of the users.

**Comment by profclems** [comment]
By default, the remote url variable is set to `origin`. I'm sure you probably changed. 

Also note that global configuration is saved at `~/.glab-cli/config/.env` which you can modify

**Comment by baurmatt** [comment]
> By default, the remote url variable is set to origin. I'm sure you probably changed.

Nope, I using the default: `origin`. In fact this repository has only one remote: `origin`:

```
$ git remote -v
origin	git@gitlab.example.org:group/subgroup1/subgroup2/ingress-nginx.git (fetch)
origin	git@gitlab.example.org:group/subgroup1/subgroup2/ingress-nginx.git (push)
```

> Also note that global configuration is saved at ~/.glab-cli/config/.env which you can modify

For this use case, I need repository specific configuration because it uses a different Gitlab instance as most of my other projects.

**Comment by profclems** [comment]
For local configs, the  `.glab-cli` folder is created in your current directory and automatically added to your .gitignore file to avoid being tracked by git.
If there is no `.gitignore`, glab creates one for you

**Comment by baurmatt** [comment]
Yep, and this works as expected :) Still this commands seems to have a problem:

```
glab config --token=$GITLAB_CODE_API_PRIVATE_TOKEN --url=https://gitlab.example.org
```

Even if the remote is `origin` this throws the `Could not find remote url for gitlab. Run git config` error.

**Comment by profclems** [comment]
I will look into that... it should have defaulted to `origin`.
However, add `--remote-var=origin`
You can also check if the `.glab-cli/config/.env` file has `GIT_REMOTE_URL_VAR=origin`

**Comment by baurmatt** [comment]
Hmm yeah, it doesn't wrote `GIT_REMOTE_URL_VAR` into that config file:

```
$ glab config --token=$GITLAB_CODE_API_PRIVATE_TOKEN --url=https://gitlab.example.org
Environment variable(s) updated
$ cat .glab-cli/config/.env
GITLAB_TOKEN=JfJ8-Qfxo7Tw95osicmR
GITLAB_URI=https://gitlab.example.org
```

**Comment by profclems** [comment]
Thanks for your feedback!

I will do a release on 14th addressing these issues alongside other features like #83   :)

**Comment by baurmatt** [comment]
Thanks! :)
