### ISSUE TITLE
Add a generic 'api' command taking curl-style arguments for making arbitrary API calls with saved authentication

### ISSUE THREAD

**Issue by jghal** [profclems/glab#970]
**Describe the feature or problem you'd like to solve**

For all the API calls that glab doesn't natively have commands for, it'd be nice to still be able to make use of the saved authentication with a generic `api` command and do JSON queries on the response. This would be similar to the `gh` CLI tools [api](https://cli.github.com/manual/gh_api) command.

**Comment by profclems** [comment]
@jghal `glab` already has the `api` command for making REST and graphql requests to the GitLab API. 

You can always use it together with the `glab alias` command to create custom commands.

**Comment by jghal** [comment]
Oh nice! I didn't see it documented [here](https://glab.readthedocs.io/en/latest/) and `glab help` after installing the deb didn't mention it. But it turns out I had an old 1.11 binary in my path and after removing that I see the command.
