### ISSUE TITLE
[QUESTION] Is it possible to comment on a line in diff?

### ISSUE THREAD

**Issue by pgrz** [profclems/glab#989]
**Describe the feature or problem you'd like to solve**
During review I mostly comment on files and suggest edits to lines, I don't see the possibility to do so - a read only view of the diff is available. Is it possible to add a comment to a file/line?

**Comment by zemzale** [comment]
There is an issue about this here #679, but nobody has done any work about it. It's a pretty substantial task, with quite a lot of work needed.

**Comment by pgrz** [comment]
I missed that one, thanks
